-- =====================================================================
-- Fragenpaket 4 (Teil 2): 112 weitere Fragen, nach Online-Prüfung freigegeben.
-- =====================================================================
insert into public.questions (category_id, author_id, source_label, text, correct, wrong_1, wrong_2, wrong_3, explanation)
select c.id, null, 'Startpaket', v.text, v.correct, v.w1, v.w2, v.w3, v.expl
  from (values
  ('Allgemeinwissen', 'Was feiern Christen an Pfingsten?', 'Die Sendung des Heiligen Geistes', 'Die Himmelfahrt Jesu', 'Die Auferstehung Jesu', 'Die Geburt Jesu', 'Der Name kommt vom griechischen „pentekoste“ (der fünfzigste Tag): Pfingsten ist der 50. Tag ab Ostersonntag mitgezählt.'),
  ('Allgemeinwissen', 'Welcher Heilige wird am 11. November mit Laternenumzügen gefeiert?', 'Sankt Martin', 'Sankt Nikolaus', 'Sankt Leonhard', 'Sankt Stephanus', 'Der Legende nach teilte Martin seinen Mantel mit einem frierenden Bettler.'),
  ('Allgemeinwissen', 'Wie viele Zentimeter misst ein Zoll?', '2,54', '2,45', '3,05', '2,25', null),
  ('Allgemeinwissen', 'Wie heißt das jüdische Lichterfest, bei dem acht Tage lang Kerzen entzündet werden?', 'Chanukka', 'Purim', 'Pessach', 'Jom Kippur', null),
  ('Allgemeinwissen', 'Wie lautet das Notsignal SOS im Morsealphabet?', '··· ––– ···', '––– ··· –––', '··· ·–· ···', '·–· ––– ·–·', 'SOS ist keine Abkürzung – „Save Our Souls“ ist nur eine nachträgliche Eselsbrücke.'),
  ('Allgemeinwissen', 'Was bedeutet das Wort „Tohuwabohu“?', 'Durcheinander', 'Festessen', 'Streitgespräch', 'Zaubertrick', 'Der Ausdruck stammt aus dem hebräischen Text der Schöpfungsgeschichte.'),
  ('Allgemeinwissen', 'Wie viele Quadratmeter hat ein Hektar?', '10.000', '1.000', '100.000', '5.000', 'Ein Hektar entspricht einem Quadrat von 100 mal 100 Metern.'),
  ('Allgemeinwissen', 'Wie viele Augen sind beim Skat insgesamt im Spiel?', '120', '100', '110', '130', 'Der Alleinspieler braucht mindestens 61 Augen, um das Spiel zu gewinnen.'),
  ('Geschichte', 'Wer war der erste Präsident der USA?', 'George Washington', 'Thomas Jefferson', 'John Adams', 'Abraham Lincoln', null),
  ('Geschichte', 'Welche Seuche wütete Mitte des 14. Jahrhunderts als „Schwarzer Tod“ in Europa?', 'Die Pest', 'Die Pocken', 'Die Cholera', 'Die Lepra', null),
  ('Geschichte', 'Wessen Expedition gelang zwischen 1519 und 1522 die erste Weltumsegelung?', 'Ferdinand Magellan', 'Vasco da Gama', 'James Cook', 'Francis Drake', 'Magellan selbst starb unterwegs auf den Philippinen.'),
  ('Geschichte', 'Welche Stadt eroberten die Osmanen im Jahr 1453?', 'Konstantinopel', 'Wien', 'Belgrad', 'Budapest', 'Die Eroberung gilt als Ende des Byzantinischen Reichs.'),
  ('Geschichte', 'In welcher Stadt wurde 1919 die Verfassung der ersten deutschen Republik beschlossen?', 'Weimar', 'Berlin', 'Frankfurt am Main', 'Bonn', null),
  ('Geschichte', 'Welcher Friedensschluss beendete 1648 den Dreißigjährigen Krieg?', 'Der Westfälische Friede', 'Der Augsburger Religionsfriede', 'Der Prager Friede', 'Der Friede von Utrecht', 'Verhandelt wurde parallel in Münster und Osnabrück.'),
  ('Geschichte', 'Mit welchem Schiff erreichten die Pilgerväter 1620 Nordamerika?', 'Mayflower', 'Santa Maria', 'Endeavour', 'Bounty', null),
  ('Geschichte', 'Welche antike Stadt grub Heinrich Schliemann ab 1871 in der heutigen Türkei aus?', 'Troja', 'Knossos', 'Karthago', 'Babylon', null),
  ('Geschichte', 'Gegen wen siegte König Otto I. im Jahr 955 in der Schlacht auf dem Lechfeld?', 'Die Ungarn', 'Die Wikinger', 'Die Slawen', 'Die Awaren', null),
  ('Geschichte', 'Welches Volk eroberte und plünderte im Jahr 410 Rom?', 'Die Westgoten', 'Die Vandalen', 'Die Ostgoten', 'Die Hunnen', 'Angeführt wurden sie von König Alarich.'),
  ('Geografie', 'Was ist die Hauptstadt von Marokko?', 'Rabat', 'Casablanca', 'Marrakesch', 'Fès', 'Casablanca ist zwar die größte Stadt Marokkos, Regierungssitz ist aber Rabat.'),
  ('Geografie', 'Was ist die Hauptstadt von Kirgisistan?', 'Bischkek', 'Duschanbe', 'Taschkent', 'Aschgabat', null),
  ('Natur & Tiere', 'Aus wie vielen Abschnitten besteht der Magen einer Kuh?', '4', '2', '3', '6', 'Pansen, Netzmagen, Blättermagen und Labmagen.'),
  ('Natur & Tiere', 'Wie heißt die baumlose Landschaft der Kältezone im hohen Norden?', 'Tundra', 'Taiga', 'Savanne', 'Pampa', 'Südlich der Tundra schließt sich die Taiga an, der große Nadelwaldgürtel.'),
  ('Natur & Tiere', 'Was ist die Kartoffel botanisch gesehen?', 'Eine Sprossknolle', 'Eine Wurzelknolle', 'Eine Frucht', 'Eine Zwiebel', 'Die eigentlichen Früchte der Kartoffel sind kleine, giftige grüne Beeren.'),
  ('Wissenschaft & Technik', 'Wer flog 1963 als erste Frau ins Weltall?', 'Valentina Tereschkowa', 'Swetlana Sawizkaja', 'Sally Ride', 'Jelena Kondakowa', 'Die Sowjetin umkreiste die Erde mit Wostok 6 fast drei Tage lang.'),
  ('Musik', 'Welches Werk von Carl Orff beginnt mit dem Chor „O Fortuna“?', 'Carmina Burana', 'Catulli Carmina', 'Der Mond', 'Die Kluge', 'Die Texte stammen aus einer mittelalterlichen Liederhandschrift, die im Kloster Benediktbeuern gefunden wurde.'),
  ('Kunst & Literatur', 'Welcher Architekt entwarf die Sagrada Família in Barcelona?', 'Antoni Gaudí', 'Le Corbusier', 'Santiago Calatrava', 'Oscar Niemeyer', 'Gaudí arbeitete über 40 Jahre an der Kirche; vollendet hat er sie nicht.'),
  ('Kunst & Literatur', 'Welcher Künstler malte 1937 das Gemälde „Guernica“?', 'Pablo Picasso', 'Joan Miró', 'Francisco de Goya', 'Juan Gris', 'Es zeigt die Zerstörung der baskischen Stadt Guernica durch einen Luftangriff.'),
  ('Kunst & Literatur', 'Wer schrieb „Der Räuber Hotzenplotz“?', 'Otfried Preußler', 'James Krüss', 'Paul Maar', 'Janosch', 'Preußler schrieb auch „Die kleine Hexe“ und „Krabat“.'),
  ('Kunst & Literatur', 'Wer schrieb die „Schachnovelle“?', 'Stefan Zweig', 'Arthur Schnitzler', 'Joseph Roth', 'Hermann Hesse', 'Der Wiener Autor schrieb sie im Exil in Brasilien; sie erschien 1942 nach seinem Tod.'),
  ('Kunst & Literatur', 'Wer gründete 1919 in Weimar das Bauhaus?', 'Walter Gropius', 'Ludwig Mies van der Rohe', 'Le Corbusier', 'Peter Behrens', 'Mies van der Rohe war ab 1930 der letzte Direktor des Bauhauses.'),
  ('Kunst & Literatur', 'Wer schrieb das Theaterstück „Der Besuch der alten Dame“?', 'Friedrich Dürrenmatt', 'Max Frisch', 'Bertolt Brecht', 'Carl Zuckmayer', null),
  ('Kunst & Literatur', 'In welchem Berg schläft laut Sage Kaiser Friedrich Barbarossa?', 'Kyffhäuser', 'Brocken', 'Watzmann', 'Zugspitze', null),
  ('Kunst & Literatur', 'Wer malte „Die Nachtwache“?', 'Rembrandt', 'Frans Hals', 'Peter Paul Rubens', 'Jan Steen', 'Das riesige Gruppenbild hängt im Rijksmuseum in Amsterdam.'),
  ('Kunst & Literatur', 'Wie heißt der junge Gascogner, der sich den drei Musketieren anschließt?', 'd’Artagnan', 'Athos', 'Porthos', 'Aramis', 'Athos, Porthos und Aramis sind die drei Musketiere selbst.'),
  ('Kunst & Literatur', 'Welcher Wiener Maler, ein Schützling Klimts, starb 1918 mit nur 28 Jahren an der Spanischen Grippe?', 'Egon Schiele', 'Oskar Kokoschka', 'Koloman Moser', 'Richard Gerstl', 'Kokoschka wurde dagegen 93 Jahre alt.'),
  ('Kunst & Literatur', 'Welcher Architekt entwarf die Glaspyramide vor dem Louvre?', 'I. M. Pei', 'Frank Gehry', 'Norman Foster', 'Renzo Piano', 'Die Pyramide wurde 1989 eröffnet und war anfangs heftig umstritten.'),
  ('Kunst & Literatur', 'Wer schuf den Vierströmebrunnen auf der Piazza Navona in Rom?', 'Gian Lorenzo Bernini', 'Francesco Borromini', 'Antonio Canova', 'Michelangelo', 'Die vier Figuren stehen für Donau, Nil, Ganges und Río de la Plata.'),
  ('Kunst & Literatur', 'In welcher Stadt steht die große Rekonstruktion des babylonischen Ischtar-Tors?', 'Berlin', 'London', 'Paris', 'Wien', 'Sie steht im Vorderasiatischen Museum im Pergamonmuseum auf der Museumsinsel.'),
  ('Allgemeinwissen', 'Welches Kleidungsstück machte der aus Franken stammende Levi Strauss weltberühmt?', 'Die Jeans', 'Den Trenchcoat', 'Die Lederhose', 'Das Polohemd', 'Levi Strauss wurde 1829 in Buttenheim in Oberfranken geboren.'),
  ('Allgemeinwissen', 'Aus wie vielen Bundesländern besteht Österreich?', '9', '8', '10', '12', 'Wien ist zugleich Bundeshauptstadt und eigenes Bundesland.'),
  ('Allgemeinwissen', 'Wie viel Karat hat reines Gold?', '24', '18', '22', '20', null),
  ('Allgemeinwissen', 'Wofür steht die Abkürzung „TÜV“?', 'Technischer Überwachungsverein', 'Technischer Überprüfungsverband', 'Technische Untersuchungsverwaltung', 'Technischer Übergabeverein', 'Die Ursprünge liegen in Dampfkessel-Überwachungsvereinen des 19. Jahrhunderts.'),
  ('Allgemeinwissen', 'Für welche Zahl steht das römische Zahlzeichen „D“?', '500', '50', '100', '1.000', null),
  ('Allgemeinwissen', 'Was bedeutet die Redewendung „Fersengeld geben“?', 'Davonlaufen', 'Jemanden bestechen', 'Schulden begleichen', 'Trinkgeld geben', null),
  ('Allgemeinwissen', 'Auf welchem Berg erhielt Mose laut Bibel die Zehn Gebote?', 'Sinai', 'Ararat', 'Tabor', 'Ölberg', null),
  ('Geschichte', 'Welcher römische Staatsmann wurde an den Iden des März 44 v. Chr. ermordet?', 'Gaius Julius Caesar', 'Augustus', 'Nero', 'Pompeius', 'Unter den Verschwörern war auch sein Vertrauter Brutus.'),
  ('Geschichte', 'Welches Volk erbaute die Bergstadt Machu Picchu in Peru?', 'Die Inka', 'Die Maya', 'Die Azteken', 'Die Olmeken', null),
  ('Geschichte', 'Welcher Reichskanzler wurde „der Eiserne Kanzler“ genannt?', 'Otto von Bismarck', 'Leo von Caprivi', 'Bernhard von Bülow', 'Theobald von Bethmann Hollweg', null),
  ('Geschichte', 'Auf welcher Insel starb Napoleon Bonaparte 1821 in der Verbannung?', 'St. Helena', 'Elba', 'Korsika', 'Malta', 'Auf Elba war er schon 1814/15 verbannt – von dort kehrte er noch einmal zurück.'),
  ('Geschichte', 'Unter welchem römischen Kaiser brannte im Jahr 64 große Teile Roms nieder?', 'Nero', 'Caligula', 'Tiberius', 'Claudius', null),
  ('Geschichte', 'Wie hieß das US-Hilfsprogramm für den Wiederaufbau Europas nach dem Zweiten Weltkrieg?', 'Marshallplan', 'Morgenthau-Plan', 'Dawes-Plan', 'Young-Plan', null),
  ('Geschichte', 'Wo wurde 1871 das Deutsche Kaiserreich ausgerufen?', 'Im Schloss Versailles', 'Im Berliner Stadtschloss', 'In der Frankfurter Paulskirche', 'Im Schloss Sanssouci', 'Die Proklamation fand im Spiegelsaal statt.'),
  ('Geschichte', 'Welcher sowjetische Partei- und Regierungschef war während der Kubakrise 1962 im Amt?', 'Nikita Chruschtschow', 'Georgi Malenkow', 'Josef Stalin', 'Michail Gorbatschow', null),
  ('Geschichte', 'Wer erhielt 1886 das Patent für den ersten Motorwagen mit Benzinmotor?', 'Carl Benz', 'Rudolf Diesel', 'Nikolaus Otto', 'August Horch', 'Seine Frau Bertha machte 1888 damit die erste Fernfahrt von Mannheim nach Pforzheim.'),
  ('Geschichte', 'Welcher Papst führte 1582 den heute gültigen Kalender ein?', 'Gregor XIII.', 'Gregor VII.', 'Pius V.', 'Sixtus V.', 'Auf den 4. Oktober folgte damals direkt der 15. Oktober 1582.'),
  ('Geschichte', 'Welche Hochkultur entwickelte die Keilschrift?', 'Die Sumerer', 'Die Ägypter', 'Die Phönizier', 'Die Hethiter', null),
  ('Geografie', 'Was ist die Hauptstadt von Litauen?', 'Vilnius', 'Riga', 'Tallinn', 'Kaunas', null),
  ('Geografie', 'Was ist die Hauptstadt von Albanien?', 'Tirana', 'Skopje', 'Podgorica', 'Pristina', null),
  ('Natur & Tiere', 'Welches dieser Tiere ist kein Insekt?', 'Zecke', 'Libelle', 'Ameise', 'Floh', 'Zecken gehören zu den Spinnentieren; ausgewachsen haben sie acht Beine.'),
  ('Natur & Tiere', 'Wie nennt man den Meeresboden an der Nordsee, der bei Ebbe trockenfällt?', 'Watt', 'Haff', 'Bodden', 'Förde', null),
  ('Natur & Tiere', 'Wie nennt man in der Jägersprache den Kot von Wild?', 'Losung', 'Lauscher', 'Lichter', 'Schweiß', 'Lauscher sind die Ohren, Lichter die Augen und Schweiß das Blut.'),
  ('Wissenschaft & Technik', 'Wie heißt der eisenhaltige rote Blutfarbstoff, der den Sauerstoff transportiert?', 'Hämoglobin', 'Myoglobin', 'Melanin', 'Bilirubin', 'Myoglobin ist sein Verwandter im Muskel, der dort Sauerstoff speichert.'),
  ('Kunst & Literatur', 'Wie heißt der Druide in den „Asterix“-Comics?', 'Miraculix', 'Majestix', 'Troubadix', 'Verleihnix', 'Im französischen Original heißt er Panoramix.'),
  ('Kunst & Literatur', 'Wer schuf die Bildergeschichte „Max und Moritz“?', 'Wilhelm Busch', 'Heinrich Hoffmann', 'Erich Kästner', 'Christian Morgenstern', 'Sie erschien 1865 und gilt als Vorläufer des Comics.'),
  ('Kunst & Literatur', 'Welche Romanfigur wohnt in der Villa Kunterbunt?', 'Pippi Langstrumpf', 'Ronja Räubertochter', 'Michel aus Lönneberga', 'Karlsson vom Dach', 'Mit ihr wohnen dort das Pferd „Kleiner Onkel“ und der Affe Herr Nilsson.'),
  ('Kunst & Literatur', 'Wer malte „Der Wanderer über dem Nebelmeer“?', 'Caspar David Friedrich', 'Philipp Otto Runge', 'Carl Spitzweg', 'Adolph Menzel', 'Das Bild um 1818 gilt als Inbegriff der deutschen Romantik.'),
  ('Kunst & Literatur', 'Wer erfand die Comicfigur Tim (im Original Tintin)?', 'Hergé', 'Albert Uderzo', 'Morris', 'André Franquin', 'Der Künstlername Hergé geht auf die vertauschten Initialen von Georges Remi zurück.'),
  ('Kunst & Literatur', 'Von welchem Künstler stammt das berühmte Aquarell „Feldhase“ von 1502?', 'Albrecht Dürer', 'Lucas Cranach der Ältere', 'Hans Holbein der Jüngere', 'Matthias Grünewald', 'Das Original liegt in der Albertina in Wien.'),
  ('Kunst & Literatur', 'Welcher Roman beginnt mit dem Satz „Call me Ishmael.“?', 'Moby-Dick', 'Robinson Crusoe', 'Die Schatzinsel', 'Zwanzigtausend Meilen unter dem Meer', 'Herman Melvilles Roman erschien 1851.'),
  ('Kunst & Literatur', 'In welcher Stadt steht die Eremitage?', 'Sankt Petersburg', 'Moskau', 'Minsk', 'Riga', 'Ein Teil der Sammlung ist im Winterpalast der Zaren untergebracht.'),
  ('Kunst & Literatur', 'Wer malte „Die Geburt der Venus“?', 'Sandro Botticelli', 'Tizian', 'Giotto', 'Fra Angelico', 'Das Bild zeigt Venus auf einer Muschel und hängt in den Uffizien in Florenz.'),
  ('Kunst & Literatur', 'Welches Heldenepos erzählt von Siegfried, Kriemhild und Hagen?', 'Nibelungenlied', 'Parzival', 'Beowulf', 'Tristan und Isolde', 'Es entstand um 1200 vermutlich im Umfeld des Passauer Bischofshofs.'),
  ('Kunst & Literatur', 'An welchem Wiener Gebäude steht „Der Zeit ihre Kunst. Der Kunst ihre Freiheit.“?', 'Secessionsgebäude', 'Burgtheater', 'Kunsthistorisches Museum', 'Albertina', 'Wegen seiner goldenen Kuppel nennen die Wiener es auch „Krauthappel“.'),
  ('Kunst & Literatur', 'Wer übersetzte jahrzehntelang die Donald-Duck-Comics ins Deutsche?', 'Erika Fuchs', 'Gudrun Penndorf', 'Mirjam Pressler', 'Hanna Johansen', 'Nach ihr ist der „Erikativ“ benannt – „seufz“, „grübel“; ihr Museum steht im oberfränkischen Schwarzenbach an der Saale.'),
  ('Kunst & Literatur', 'Wer erzählt in „Der große Gatsby“ die Geschichte?', 'Nick Carraway', 'Jay Gatsby', 'Tom Buchanan', 'George Wilson', null),
  ('Allgemeinwissen', 'In welchem Artikel des Grundgesetzes steht „Die Würde des Menschen ist unantastbar“?', 'Artikel 1', 'Artikel 3', 'Artikel 5', 'Artikel 20', null),
  ('Allgemeinwissen', 'In welcher Stadt hat das Bundesverfassungsgericht seinen Sitz?', 'Karlsruhe', 'Leipzig', 'Kassel', 'Erfurt', 'In Karlsruhe sitzt auch der Bundesgerichtshof.'),
  ('Allgemeinwissen', 'Wie heißt der Gott des Meeres in der römischen Mythologie?', 'Neptun', 'Poseidon', 'Merkur', 'Vulcanus', 'Poseidon ist sein griechisches Gegenstück.'),
  ('Allgemeinwissen', 'Für wie viele Jahre wird der deutsche Bundespräsident gewählt?', '5', '4', '6', '7', 'Eine anschließende Wiederwahl ist nur einmal zulässig.'),
  ('Allgemeinwissen', 'Welcher katholische Feiertag fällt immer auf den Donnerstag 60 Tage nach Ostersonntag?', 'Fronleichnam', 'Christi Himmelfahrt', 'Mariä Himmelfahrt', 'Allerheiligen', 'In Bayern ist Fronleichnam gesetzlicher Feiertag und wird mit Prozessionen gefeiert.'),
  ('Allgemeinwissen', 'Wie viele Nullen hat eine Billion im Deutschen?', '12', '9', '15', '18', 'Das englische „billion“ entspricht dagegen nur der deutschen Milliarde.'),
  ('Allgemeinwissen', 'Wie viele Stück sind ein „Gros“?', '144', '100', '120', '72', 'Ein Gros sind zwölf Dutzend.'),
  ('Geschichte', 'Wer erreichte 1492 im Auftrag der spanischen Krone Amerika?', 'Christoph Kolumbus', 'Vasco da Gama', 'Ferdinand Magellan', 'Amerigo Vespucci', 'Kolumbus glaubte bis zu seinem Tod, einen Seeweg nach Asien gefunden zu haben.'),
  ('Geschichte', 'Wer entwickelte um 1450 in Mainz den Buchdruck mit beweglichen Metalllettern?', 'Johannes Gutenberg', 'Albrecht Dürer', 'Jakob Fugger', 'Nikolaus von Kues', 'Sein bekanntestes Werk ist die 42-zeilige Gutenberg-Bibel.'),
  ('Geschichte', 'In welchem Kraftwerk ereignete sich 1986 eine verheerende Reaktorkatastrophe?', 'Tschernobyl', 'Fukushima', 'Three Mile Island', 'Sellafield', null),
  ('Geschichte', 'Welcher Bundeskanzler kniete 1970 am Ehrenmal des Warschauer Ghettos nieder?', 'Willy Brandt', 'Helmut Schmidt', 'Kurt Georg Kiesinger', 'Ludwig Erhard', null),
  ('Geschichte', 'Wer führte die Germanen im Jahr 9 n. Chr. in der Varusschlacht an?', 'Arminius', 'Vercingetorix', 'Marbod', 'Widukind', 'Im 19. Jahrhundert wurde er als „Hermann der Cherusker“ zum Nationalhelden.'),
  ('Geschichte', 'Wer war der erste Bundespräsident der Bundesrepublik Deutschland?', 'Theodor Heuss', 'Heinrich Lübke', 'Walter Scheel', 'Gustav Heinemann', null),
  ('Geschichte', 'Welcher spartanische König fiel 480 v. Chr. in der Schlacht bei den Thermopylen?', 'Leonidas', 'Perikles', 'Lykurg', 'Xerxes', null),
  ('Geschichte', 'In welchem Frankfurter Gebäude tagte 1848/49 die erste deutsche Nationalversammlung?', 'Paulskirche', 'Römer', 'Kaiserdom', 'Alte Oper', null),
  ('Geschichte', 'In welchem Jahr belagerten die Osmanen Wien zum zweiten Mal?', '1683', '1529', '1618', '1701', 'Die Schlacht am Kahlenberg beendete die Belagerung.'),
  ('Geschichte', 'Wie hieß Straubing zur Römerzeit?', 'Sorviodurum', 'Castra Regina', 'Batavis', 'Augusta Vindelicum', 'Castra Regina war Regensburg, Batavis Passau und Augusta Vindelicum Augsburg.'),
  ('Geografie', 'Was ist die Hauptstadt von Slowenien?', 'Ljubljana', 'Zagreb', 'Bratislava', 'Maribor', null),
  ('Geografie', 'Was ist die Hauptstadt von Äthiopien?', 'Addis Abeba', 'Asmara', 'Khartum', 'Mogadischu', 'Addis Abeba ist auch Sitz der Afrikanischen Union.'),
  ('Geografie', 'An welchem Fluss liegt Bagdad?', 'Tigris', 'Euphrat', 'Jordan', 'Orontes', null),
  ('Natur & Tiere', 'Wie heißen die roten Blutkörperchen in der Fachsprache?', 'Erythrozyten', 'Leukozyten', 'Thrombozyten', 'Lymphozyten', null),
  ('Natur & Tiere', 'Wie heißt in der Jägersprache die Paarungszeit des Rothirschs?', 'Brunft', 'Balz', 'Ranz', 'Rauschzeit', 'Balz sagt man bei Vögeln, Ranz bei Fuchs und Marder, Rauschzeit beim Wildschwein.'),
  ('Natur & Tiere', 'Welches dieser Meerestiere ist ein Fisch?', 'Seepferdchen', 'Seestern', 'Tintenfisch', 'Seegurke', 'Beim Seepferdchen trägt das Männchen die Eier in einer Bruttasche aus.'),
  ('Film & Serien', 'Welches Tier ist Pumbaa in „Der König der Löwen“?', 'Ein Warzenschwein', 'Ein Erdmännchen', 'Eine Hyäne', 'Ein Pavian', 'Sein bester Freund ist das Erdmännchen Timon.'),
  ('Kunst & Literatur', 'Wer schrieb „Die Abenteuer des Tom Sawyer“?', 'Mark Twain', 'Jack London', 'Charles Dickens', 'Herman Melville', 'Tom Sawyers Freund Huckleberry Finn bekam später ein eigenes Buch.'),
  ('Kunst & Literatur', 'Welche Märchenfigur lässt ihr langes Haar aus einem Turm herab?', 'Rapunzel', 'Dornröschen', 'Schneewittchen', 'Aschenputtel', 'Benannt ist sie nach der Salatpflanze, die ihr Vater für die Mutter aus dem Garten der Zauberin stahl.'),
  ('Kunst & Literatur', 'Aus welcher Stadt entführte laut Sage der Rattenfänger die Kinder?', 'Hameln', 'Hannover', 'Göttingen', 'Bremen', 'Laut Sage verschwanden dort 1284 genau 130 Kinder.'),
  ('Kunst & Literatur', 'Wer malte das Bild „Der arme Poet“ mit dem Regenschirm unter dem Dach?', 'Carl Spitzweg', 'Wilhelm Leibl', 'Franz von Stuck', 'Franz von Lenbach', 'Spitzweg war ausgebildeter Apotheker und lebte in München.'),
  ('Kunst & Literatur', 'Welcher Baustil ist typisch für Spitzbögen, Rippengewölbe und Strebewerk?', 'Gotik', 'Romanik', 'Renaissance', 'Barock', 'Der Kölner Dom ist eines der bekanntesten Beispiele.'),
  ('Kunst & Literatur', 'Wer schrieb den Roman „Die Blechtrommel“?', 'Günter Grass', 'Heinrich Böll', 'Siegfried Lenz', 'Martin Walser', 'Hauptfigur Oskar Matzerath beschließt mit drei Jahren, nicht mehr zu wachsen.'),
  ('Kunst & Literatur', 'Wer schrieb „Hundert Jahre Einsamkeit“?', 'Gabriel García Márquez', 'Mario Vargas Llosa', 'Jorge Luis Borges', 'Isabel Allende', 'Der Roman spielt im fiktiven Dorf Macondo.'),
  ('Kunst & Literatur', 'Welche Künstlergruppe gründeten Wassily Kandinsky und Franz Marc 1911 in München?', 'Der Blaue Reiter', 'Die Brücke', 'Wiener Secession', 'Neue Sachlichkeit', 'Viele ihrer Werke zeigt heute das Lenbachhaus in München.'),
  ('Kunst & Literatur', 'Wer schrieb das Gedicht, das mit „Ich weiß nicht, was soll es bedeuten“ beginnt?', 'Heinrich Heine', 'Theodor Fontane', 'Friedrich Hölderlin', 'Eduard Mörike', 'Es handelt von der Loreley, die auf einem Felsen über dem Rhein ihr Haar kämmt.'),
  ('Kunst & Literatur', 'Welcher Künstler wurde mit Bildern aus getropfter und geschleuderter Farbe („Drip Painting“) berühmt?', 'Jackson Pollock', 'Mark Rothko', 'Roy Lichtenstein', 'Willem de Kooning', null),
  ('Kunst & Literatur', 'Welcher Bildhauer ist für extrem schlanke, langgezogene Bronzefiguren bekannt?', 'Alberto Giacometti', 'Henry Moore', 'Constantin Brâncuși', 'Ernst Barlach', 'Sein Porträt war auf der früheren Schweizer 100-Franken-Note abgebildet.'),
  ('Kunst & Literatur', 'Wie heißt die Hauptfigur in Thomas Manns Roman „Der Zauberberg“?', 'Hans Castorp', 'Tonio Kröger', 'Gustav von Aschenbach', 'Felix Krull', 'Aus einem dreiwöchigen Besuch im Sanatorium in Davos werden sieben Jahre.'),
  ('Kunst & Literatur', 'Welcher Maler schuf den Isenheimer Altar?', 'Matthias Grünewald', 'Albrecht Dürer', 'Lucas Cranach der Ältere', 'Hans Holbein der Ältere', 'Der Altar ist heute im Museum Unterlinden in Colmar zu sehen.')
  ) as v(category, text, correct, w1, w2, w3, expl)
  join public.categories c on c.name = v.category
 where not exists (select 1 from public.questions q where q.text = v.text);
