-- =====================================================================
-- Fragenpaket 2: 91 Pub-Quiz-Fragen (Fakten aus brainpower.events und
-- mentimeter.com, eigene Formulierungen). Autor = „Startpaket“.
-- Vorhandene Fragen mit gleichem Text werden übersprungen.
-- =====================================================================

insert into public.questions (category_id, author_id, source_label, text, correct, wrong_1, wrong_2, wrong_3, explanation)
select c.id, null, 'Startpaket', v.text, v.correct, v.w1, v.w2, v.w3, v.expl
  from (values
  ('Allgemeinwissen', 'Wie viele Geister jagen Pac-Man im Original-Spiel?', '4', '3', '5', '6', 'Blinky, Pinky, Inky und Clyde.'),
  ('Allgemeinwissen', 'Wie schreibt man „Postbote“ ohne O?', 'Briefträger', 'Pstbte', 'Pstbote', 'Postbte', 'Ein Scherz: einfach ein anderes Wort nehmen.'),
  ('Allgemeinwissen', 'Wofür stand der Sendername RTL ursprünglich?', 'Radio Télévision Luxembourg', 'Radio Television Leipzig', 'Rundfunk Television Lindau', 'Radio Transnational Live', null),
  ('Allgemeinwissen', 'Welches Symbol gehört zum Evangelisten Markus?', 'Löwe', 'Adler', 'Stier', 'Engel', 'Matthäus: Mensch/Engel, Lukas: Stier, Johannes: Adler.'),
  ('Allgemeinwissen', 'Wie heißt die Universität in Frankfurt am Main offiziell?', 'Johann Wolfgang Goethe-Universität', 'Friedrich-Schiller-Universität', 'Ludwig-Maximilians-Universität', 'Humboldt-Universität', null),
  ('Allgemeinwissen', 'Wie viele Monate haben 28 Tage?', 'Alle 12', '1', '4', '11', 'Jeder Monat hat mindestens 28 Tage.'),
  ('Allgemeinwissen', 'Toms Mutter hat drei Kinder: Tick, Trick und …?', 'Tom', 'Track', 'Trock', 'Tim', null),
  ('Allgemeinwissen', 'Wie viele Tiere jeder Art nahm Mose mit auf die Arche?', 'Keine', '2', '7', '1', 'Mit der Arche fuhr Noah, nicht Mose.'),
  ('Allgemeinwissen', 'Was liegt zwischen Meer und Land?', '„und“', 'Der Strand', 'Die Küste', 'Das Watt', 'Ein Wortspiel: Meer UND Land.'),
  ('Allgemeinwissen', 'Wie viele Minuten hat eine Woche?', '10.080', '8.640', '10.800', '12.040', '7 × 24 × 60.'),
  ('Allgemeinwissen', 'Wie viele Augen hat ein normaler Spielwürfel insgesamt?', '21', '18', '24', '36', '1 + 2 + 3 + 4 + 5 + 6.'),
  ('Allgemeinwissen', 'Welche Krankheit war früher auf langen Seereisen gefürchtet, weil Vitamin C fehlte?', 'Skorbut', 'Pest', 'Cholera', 'Malaria', null),
  ('Allgemeinwissen', 'Wie nennt man die Kunst des schönen Schreibens?', 'Kalligrafie', 'Typografie', 'Lithografie', 'Stenografie', null),
  ('Allgemeinwissen', 'In welchem Jahr wurde in Deutschland und Österreich der Euro als Bargeld eingeführt?', '2002', '1999', '2001', '2000', 'Als Buchgeld gab es ihn schon seit 1999.'),
  ('Geschichte', 'Wer verfasste hauptsächlich die amerikanische Unabhängigkeitserklärung?', 'Thomas Jefferson', 'George Washington', 'Benjamin Franklin', 'Abraham Lincoln', null),
  ('Geschichte', 'In welcher Stadt wurde John F. Kennedy 1963 erschossen?', 'Dallas', 'Houston', 'Washington', 'Chicago', null),
  ('Geschichte', 'Wer erreichte 1953 als Erste den Gipfel des Mount Everest?', 'Edmund Hillary und Tenzing Norgay', 'Reinhold Messner und Peter Habeler', 'George Mallory und Andrew Irvine', 'Roald Amundsen und Robert Scott', null),
  ('Geschichte', 'Welches Ereignis gilt als Auslöser des Dreißigjährigen Kriegs?', 'Der Prager Fenstersturz', 'Der Westfälische Friede', 'Die Bartholomäusnacht', 'Der Augsburger Religionsfrieden', '1618 auf der Prager Burg.'),
  ('Geschichte', 'Welcher Kongress ordnete 1814/15 Europa nach Napoleon neu?', 'Der Wiener Kongress', 'Der Berliner Kongress', 'Der Pariser Kongress', 'Der Frankfurter Fürstentag', null),
  ('Geschichte', 'Wer war von 1981 bis 1995 Präsident Frankreichs?', 'François Mitterrand', 'Jacques Chirac', 'Valéry Giscard d’Estaing', 'Charles de Gaulle', null),
  ('Geschichte', 'In welchem Jahr wurden die Vereinten Nationen gegründet?', '1945', '1919', '1949', '1955', null),
  ('Geschichte', 'Wer war der letzte Zar Russlands?', 'Nikolaus II.', 'Alexander III.', 'Peter der Große', 'Iwan der Schreckliche', null),
  ('Geschichte', 'Welcher Feldherr überquerte mit Kriegselefanten die Alpen?', 'Hannibal', 'Julius Caesar', 'Alexander der Große', 'Attila', null),
  ('Geschichte', 'Welcher berüchtigte Gangsterboss beherrschte in den 1920ern Chicago?', 'Al Capone', 'Lucky Luciano', 'John Dillinger', 'Bugs Moran', null),
  ('Geschichte', 'Wer entdeckte, dass sich die Erde um die Sonne dreht?', 'Nikolaus Kopernikus', 'Galileo Galilei', 'Johannes Kepler', 'Isaac Newton', null),
  ('Geografie', 'Welchen Beinamen trägt Rom?', 'Die Ewige Stadt', 'Die Goldene Stadt', 'Die Stadt der Liebe', 'Die Weiße Stadt', null),
  ('Geografie', 'Was ist die Hauptstadt von Kenia?', 'Nairobi', 'Mombasa', 'Daressalam', 'Kampala', null),
  ('Geografie', 'Aus wie vielen Kantonen besteht die Schweiz?', '26', '20', '23', '30', null),
  ('Geografie', 'Welches ist der höchste Berg der USA?', 'Denali', 'Mount Whitney', 'Mount Rainier', 'Mount Elbert', 'Früher Mount McKinley, rund 6190 Meter, in Alaska.'),
  ('Geografie', 'Welcher Fluss gilt meist als der längste der Welt?', 'Nil', 'Amazonas', 'Jangtse', 'Mississippi', 'Rund 6650 km; manche Messungen sehen den Amazonas vorn.'),
  ('Geografie', 'Welches ist das flächenmäßig kleinste deutsche Bundesland?', 'Bremen', 'Hamburg', 'Berlin', 'Saarland', null),
  ('Geografie', 'Welcher Kontinent liegt in allen vier Hemisphären?', 'Afrika', 'Asien', 'Südamerika', 'Europa', 'Afrika wird vom Äquator und vom Nullmeridian geschnitten.'),
  ('Geografie', 'Durch welchen Fluss entstand der Grand Canyon?', 'Colorado', 'Mississippi', 'Rio Grande', 'Columbia', null),
  ('Geografie', 'Was ist die Hauptstadt des US-Bundesstaats New York?', 'Albany', 'New York City', 'Buffalo', 'Rochester', null),
  ('Geografie', 'Welches ist die größte Wüste der Erde?', 'Antarktis', 'Sahara', 'Gobi', 'Arabische Wüste', 'Wüste heißt: kaum Niederschlag – auch Eis kann Wüste sein.'),
  ('Geografie', 'Was ist die Hauptstadt von Kanada?', 'Ottawa', 'Toronto', 'Montreal', 'Vancouver', null),
  ('Geografie', 'In welcher Stadt sitzt die berühmte Statue der „Kleinen Meerjungfrau“?', 'Kopenhagen', 'Oslo', 'Stockholm', 'Amsterdam', null),
  ('Geografie', 'Welches Land hat eine Nationalflagge aus zwei übereinanderliegenden Dreiecken?', 'Nepal', 'Bhutan', 'Brunei', 'Sri Lanka', 'Es ist die einzige Nationalflagge, die kein Rechteck ist.'),
  ('Geografie', 'Wie viele Sterne sind auf der Flagge Chinas?', '5', '1', '4', '6', null),
  ('Geografie', 'Was ist die Hauptstadt von Bulgarien?', 'Sofia', 'Bukarest', 'Belgrad', 'Skopje', null),
  ('Geografie', 'Wie viele europäische Hauptstädte liegen an der Donau?', '4', '2', '3', '5', 'Wien, Bratislava, Budapest und Belgrad.'),
  ('Natur & Tiere', 'Welcher Vogel ist der schnellste der Welt?', 'Wanderfalke', 'Steinadler', 'Mauersegler', 'Strauß', 'Im Sturzflug über 300 km/h.'),
  ('Natur & Tiere', 'Wie heißt eine Gruppe Krähen auf Englisch?', 'A murder', 'A flock', 'A party', 'A crowd', '„A murder of crows“.'),
  ('Natur & Tiere', 'Welches Tier gilt im Verhältnis zu seinem Gewicht als das stärkste der Welt?', 'Mistkäfer', 'Ameise', 'Gorilla', 'Nashornkäfer', null),
  ('Natur & Tiere', 'Wie heißt die Angst vor großen Höhen?', 'Akrophobie', 'Agoraphobie', 'Arachnophobie', 'Klaustrophobie', null),
  ('Natur & Tiere', 'Was sind „Pink Lady“ und „Granny Smith“?', 'Apfelsorten', 'Rosensorten', 'Birnensorten', 'Cocktails', null),
  ('Natur & Tiere', 'Wie viele Gehörknöchelchen hat ein Mensch in jedem Ohr?', '3', '1', '2', '5', 'Hammer, Amboss und Steigbügel.'),
  ('Natur & Tiere', 'Wogegen wirken Antibiotika?', 'Bakterien', 'Viren', 'Pilze', 'Allergien', null),
  ('Wissenschaft & Technik', 'Welches chemische Symbol hat Silber?', 'Ag', 'Si', 'Sr', 'Au', 'Von lateinisch argentum.'),
  ('Wissenschaft & Technik', 'In welcher Einheit misst man den elektrischen Widerstand?', 'Ohm', 'Volt', 'Ampere', 'Watt', null),
  ('Wissenschaft & Technik', 'Wie lautet der Satz des Pythagoras?', 'a² + b² = c²', 'a + b = c', 'a² · b² = c²', 'a² − b² = c', null),
  ('Wissenschaft & Technik', 'Welcher Planet ist der heißeste unseres Sonnensystems?', 'Venus', 'Merkur', 'Mars', 'Jupiter', 'Ihre dichte Atmosphäre hält die Hitze fest.'),
  ('Wissenschaft & Technik', 'Wie viele Flächen hat ein Dodekaeder?', '12', '8', '10', '20', null),
  ('Wissenschaft & Technik', 'Wie viele chemische Elemente sind im Periodensystem bekannt?', '118', '92', '108', '126', null),
  ('Wissenschaft & Technik', 'Wie hieß Amazon ursprünglich?', 'Cadabra', 'Bookstack', 'Rainforest', 'Bezos Books', null),
  ('Wissenschaft & Technik', 'Welche Firma hat ihren Sitz in Redmond im US-Bundesstaat Washington?', 'Microsoft', 'Amazon', 'Apple', 'Google', null),
  ('Wissenschaft & Technik', 'Welche Firma baute das legendäre Handy 3310?', 'Nokia', 'Siemens', 'Motorola', 'Sony Ericsson', null),
  ('Wissenschaft & Technik', 'Welche Modellnummer trägt der bekannteste Sportwagen von Porsche?', '911', '356', '944', '718', null),
  ('Sport', 'Für welches NBA-Team spielte Dirk Nowitzki seine ganze Karriere?', 'Dallas Mavericks', 'San Antonio Spurs', 'Los Angeles Lakers', 'Houston Rockets', null),
  ('Sport', 'Wo fanden die Olympischen Sommerspiele 1992 statt?', 'Barcelona', 'Atlanta', 'Seoul', 'Sydney', null),
  ('Sport', 'Welcher Golfer hat die meisten Major-Turniere gewonnen?', 'Jack Nicklaus', 'Tiger Woods', 'Arnold Palmer', 'Gary Player', '18 Major-Siege.'),
  ('Sport', 'Wie hieß die Firma Nike ursprünglich?', 'Blue Ribbon Sports', 'Swoosh Inc.', 'Oregon Running', 'Track & Field Co.', null),
  ('Sport', 'Wer gewann 1993 die allererste UEFA Champions League?', 'Olympique Marseille', 'AC Mailand', 'FC Barcelona', 'Ajax Amsterdam', null),
  ('Sport', 'Wer gilt als erster von Red Bull gesponserter Sportler?', 'Gerhard Berger', 'Niki Lauda', 'Felix Baumgartner', 'Hermann Maier', null),
  ('Sport', 'Wie lautet der Vorname von Fußball-Legende Maradona?', 'Diego', 'Lionel', 'Carlos', 'Juan', null),
  ('Sport', 'Welche Sportart gilt als Nationalsport Japans?', 'Sumo', 'Judo', 'Baseball', 'Karate', null),
  ('Sport', 'Bei welchem Tennisturnier müssen Spieler komplett in Weiß antreten?', 'Wimbledon', 'US Open', 'French Open', 'Australian Open', null),
  ('Sport', 'Was unterscheidet Skeleton vom Rennrodeln?', 'Man liegt bäuchlings, Kopf voraus', 'Man fährt im Stehen', 'Man sitzt zu zweit', 'Man fährt ohne Helm', null),
  ('Sport', 'Wie hoch hängt ein Basketballkorb?', '3,05 m', '2,85 m', '3,25 m', '2,95 m', 'Genau 10 Fuß.'),
  ('Film & Serien', 'Wie heißt der Held der Videospielreihe „God of War“?', 'Kratos', 'Ares', 'Atreus', 'Zeus', null),
  ('Film & Serien', 'Welcher war der erste abendfüllende Disney-Zeichentrickfilm?', 'Schneewittchen und die sieben Zwerge', 'Pinocchio', 'Bambi', 'Fantasia', '1937.'),
  ('Film & Serien', 'Wer hat die meisten Oscars aller Zeiten gewonnen?', 'Walt Disney', 'Steven Spielberg', 'Meryl Streep', 'John Williams', null),
  ('Film & Serien', 'Welche Figur spielten sowohl Robert Downey Jr. als auch Benedict Cumberbatch?', 'Sherlock Holmes', 'Doctor Strange', 'Iron Man', 'James Bond', null),
  ('Film & Serien', 'In welchem Disney-Film kommt das Lied „I’ll Make a Man Out of You“ vor?', 'Mulan', 'Hercules', 'Pocahontas', 'Der König der Löwen', null),
  ('Film & Serien', 'Welche Farbe haben Micky Maus’ Schuhe?', 'Gelb', 'Rot', 'Schwarz', 'Weiß', null),
  ('Film & Serien', 'Wie sollte Micky Maus ursprünglich heißen?', 'Mortimer Mouse', 'Marvin Mouse', 'Max Mouse', 'Monty Mouse', null),
  ('Film & Serien', 'In welcher Stadt steht das europäische Disneyland?', 'Paris', 'London', 'Madrid', 'München', null),
  ('Film & Serien', 'Welche Schauspielerin spielte Cruella de Vil im Film von 2021?', 'Emma Stone', 'Glenn Close', 'Emma Watson', 'Margot Robbie', 'Glenn Close spielte sie 1996.'),
  ('Film & Serien', 'In welchem Jahr kam Disneys „Cinderella“ in die Kinos?', '1950', '1937', '1959', '1967', null),
  ('Musik', 'In welchem Fach hat Queen-Gitarrist Brian May einen Doktortitel?', 'Astrophysik', 'Medizin', 'Chemie', 'Musikwissenschaft', null),
  ('Musik', 'Wer war der Sänger von Linkin Park bis 2017?', 'Chester Bennington', 'Chris Cornell', 'Mike Shinoda', 'Dave Grohl', null),
  ('Essen & Trinken', 'Was ist Beaujolais?', 'Ein Rotwein', 'Ein Käse', 'Ein Weißwein', 'Ein Likör', null),
  ('Essen & Trinken', 'Welche dieser Soßen ist nicht vegan?', 'Worcestershiresauce', 'Sojasauce', 'Ketchup', 'Tabasco', 'Klassisch sind Sardellen drin.'),
  ('Essen & Trinken', 'Welches ist das meistverkaufte Stout-Bier der Welt?', 'Guinness', 'Murphy’s', 'Beamish', 'Kilkenny', null),
  ('Essen & Trinken', 'Welches Fleisch gehört klassisch in einen Shepherd’s Pie?', 'Lamm', 'Rind', 'Schwein', 'Huhn', 'Mit Rind heißt er Cottage Pie.'),
  ('Essen & Trinken', 'Was unterscheidet Cognac von anderem Weinbrand?', 'Er stammt aus der Region Cognac in Frankreich', 'Er wird aus Äpfeln gebrannt', 'Er reift nur ein Jahr', 'Er enthält Zucker', null),
  ('Essen & Trinken', 'Aus welcher Stadt stammt das Nudelgericht „Cacio e Pepe“?', 'Rom', 'Neapel', 'Bologna', 'Mailand', null),
  ('Essen & Trinken', 'In welchem Land trinkt man pro Kopf am meisten Kaffee?', 'Finnland', 'Italien', 'Deutschland', 'Brasilien', null),
  ('Kunst & Literatur', 'Wer malte „Der Schrei“?', 'Edvard Munch', 'Gustav Klimt', 'Egon Schiele', 'Ernst Ludwig Kirchner', null),
  ('Kunst & Literatur', 'Welcher Renaissance-Maler ist im Pantheon in Rom begraben?', 'Raffael', 'Michelangelo', 'Leonardo da Vinci', 'Tizian', null),
  ('Kunst & Literatur', 'Wo sind die Parthenon-Skulpturen aus Athen heute größtenteils ausgestellt?', 'Im British Museum in London', 'Im Louvre in Paris', 'In der Akropolis in Athen', 'Im Pergamonmuseum in Berlin', null)
  ) as v(category, text, correct, w1, w2, w3, expl)
  join public.categories c on c.name = v.category
 where not exists (select 1 from public.questions q where q.text = v.text);
