-- =====================================================================
-- Startpaket: 100 Fragen (10 pro Kategorie), eigene Formulierungen im
-- Pub-Quiz-Stil. Autor = niemand, angezeigt als „Startpaket“.
-- Läuft nur einmal; vorhandene Fragen mit gleichem Text werden übersprungen.
-- =====================================================================

insert into public.questions (category_id, author_id, source_label, text, correct, wrong_1, wrong_2, wrong_3, explanation)
select c.id, null, 'Startpaket', v.text, v.correct, v.w1, v.w2, v.w3, v.expl
  from (values
  ('Allgemeinwissen', 'Wie viele Tage hat ein Schaltjahr?', '366', '365', '364', '367', null),
  ('Allgemeinwissen', 'Welche Farbe entsteht, wenn man Blau und Gelb mischt?', 'Grün', 'Violett', 'Orange', 'Braun', null),
  ('Allgemeinwissen', 'Wie viele Felder hat ein Schachbrett?', '64', '48', '81', '100', '8 × 8 Felder.'),
  ('Allgemeinwissen', 'Wie viele Minuten hat ein Tag?', '1440', '1240', '1640', '2400', '24 × 60 = 1440.'),
  ('Allgemeinwissen', 'Welches Sprichwort zeigen diese Emojis: 🐦✋ > 🕊️🏠', 'Lieber den Spatz in der Hand als die Taube auf dem Dach', 'Ein Vogel kommt selten allein', 'Wer zuerst kommt, mahlt zuerst', 'Morgenstund hat Gold im Mund', null),
  ('Allgemeinwissen', 'Was ist die Hauptstadt von Bayern?', 'München', 'Nürnberg', 'Augsburg', 'Regensburg', null),
  ('Allgemeinwissen', 'In welcher Stadt steht das Brandenburger Tor?', 'Berlin', 'Potsdam', 'Brandenburg an der Havel', 'Hamburg', null),
  ('Allgemeinwissen', 'Wie viele Ecken hat ein Oktaeder?', '6', '8', '12', '4', 'Ein Oktaeder hat 8 Flächen, 12 Kanten und 6 Ecken.'),
  ('Allgemeinwissen', 'Welcher englische Wochentag ist nach dem Planeten Saturn benannt?', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', null),
  ('Allgemeinwissen', 'Wie viele Zähne hat ein Erwachsener normalerweise, Weisheitszähne mitgezählt?', '32', '28', '30', '36', null),
  ('Geschichte', 'In welchem Jahr fiel die Berliner Mauer?', '1989', '1987', '1990', '1991', 'Am 9. November 1989.'),
  ('Geschichte', 'Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?', 'Konrad Adenauer', 'Ludwig Erhard', 'Willy Brandt', 'Theodor Heuss', 'Theodor Heuss war der erste Bundespräsident.'),
  ('Geschichte', 'In welchem Jahr betraten erstmals Menschen den Mond?', '1969', '1965', '1972', '1961', 'Apollo 11 im Juli 1969.'),
  ('Geschichte', 'Welches Schiff sank 1912 nach der Kollision mit einem Eisberg?', 'Titanic', 'Lusitania', 'Britannic', 'Bismarck', null),
  ('Geschichte', 'Wer wurde im Jahr 800 in Rom zum Kaiser gekrönt?', 'Karl der Große', 'Otto der Große', 'Friedrich Barbarossa', 'Ludwig der Fromme', null),
  ('Geschichte', 'In welchem Jahr begann der Erste Weltkrieg?', '1914', '1912', '1916', '1918', null),
  ('Geschichte', 'Welcher Pharao wurde durch die Entdeckung seines fast unberührten Grabes 1922 berühmt?', 'Tutanchamun', 'Ramses II.', 'Cheops', 'Echnaton', null),
  ('Geschichte', 'Wer veröffentlichte 1517 in Wittenberg seine 95 Thesen?', 'Martin Luther', 'Johannes Calvin', 'Huldrych Zwingli', 'Philipp Melanchthon', null),
  ('Geschichte', 'Welche antike Stadt wurde im Jahr 79 beim Ausbruch des Vesuvs verschüttet?', 'Pompeji', 'Karthago', 'Troja', 'Ostia', null),
  ('Geschichte', 'In welchem Jahr fand das erste Oktoberfest statt?', '1810', '1795', '1850', '1871', 'Anlass war die Hochzeit von Kronprinz Ludwig und Therese von Sachsen-Hildburghausen.'),
  ('Geografie', 'Was ist die Hauptstadt von Australien?', 'Canberra', 'Sydney', 'Melbourne', 'Perth', null),
  ('Geografie', 'Was ist die Hauptstadt der Mongolei?', 'Ulaanbaatar', 'Astana', 'Bischkek', 'Taschkent', null),
  ('Geografie', 'Welcher ist der längste Fluss Europas?', 'Wolga', 'Donau', 'Rhein', 'Dnepr', 'Die Wolga ist rund 3500 km lang.'),
  ('Geografie', 'Wie viele Nachbarländer hat Deutschland?', '9', '8', '10', '7', 'Dänemark, Polen, Tschechien, Österreich, Schweiz, Frankreich, Luxemburg, Belgien und die Niederlande.'),
  ('Geografie', 'An welchem Fluss liegt Straubing?', 'Donau', 'Isar', 'Inn', 'Regen', null),
  ('Geografie', 'Welches Land hat eine rot-weiße Flagge mit einem Ahornblatt?', 'Kanada', 'Japan', 'Schweiz', 'Dänemark', null),
  ('Geografie', 'In welchem Land liegt der Kilimandscharo?', 'Tansania', 'Kenia', 'Uganda', 'Äthiopien', null),
  ('Geografie', 'Welches ist das flächenmäßig größte Land der Erde?', 'Russland', 'Kanada', 'China', 'USA', null),
  ('Geografie', 'Welcher Ozean ist der größte?', 'Pazifik', 'Atlantik', 'Indischer Ozean', 'Arktischer Ozean', null),
  ('Geografie', 'Durch welche dieser Hauptstädte fließt die Donau nicht?', 'Prag', 'Wien', 'Budapest', 'Bratislava', 'Durch Prag fließt die Moldau.'),
  ('Natur & Tiere', 'Wie viele Herzen hat ein Oktopus?', '3', '1', '2', '8', 'Zwei pumpen Blut durch die Kiemen, eins durch den Körper.'),
  ('Natur & Tiere', 'Welches ist nach heutigem Wissen das größte Tier, das je gelebt hat?', 'Blauwal', 'Argentinosaurus', 'Pottwal', 'Mammut', null),
  ('Natur & Tiere', 'Wie viele Beine hat eine Spinne?', '8', '6', '10', '12', null),
  ('Natur & Tiere', 'Welches dieser Säugetiere kann aktiv fliegen?', 'Fledermaus', 'Flughörnchen', 'Kurzkopfgleitbeutler', 'Riesengleiter', 'Die anderen drei können nur gleiten.'),
  ('Natur & Tiere', 'Wie heißt ein männliches Schwein?', 'Eber', 'Bock', 'Hengst', 'Widder', null),
  ('Natur & Tiere', 'Welcher Baum trägt Eicheln?', 'Eiche', 'Buche', 'Kastanie', 'Linde', null),
  ('Natur & Tiere', 'Welcher Vogel kann rückwärts fliegen?', 'Kolibri', 'Eisvogel', 'Schwalbe', 'Specht', null),
  ('Natur & Tiere', 'Wie lange ist eine Elefantenkuh ungefähr trächtig?', '22 Monate', '9 Monate', '12 Monate', '36 Monate', 'Die längste Tragzeit aller Landsäugetiere.'),
  ('Natur & Tiere', 'Welches ist das schnellste Landtier?', 'Gepard', 'Löwe', 'Gabelbock', 'Springbock', null),
  ('Natur & Tiere', 'Welcher heimische Nadelbaum verliert im Herbst seine Nadeln?', 'Lärche', 'Fichte', 'Kiefer', 'Tanne', null),
  ('Wissenschaft & Technik', 'Welches chemische Symbol hat Gold?', 'Au', 'Ag', 'Go', 'Gd', 'Von lateinisch aurum. Ag ist Silber.'),
  ('Wissenschaft & Technik', 'Welcher Planet ist der Sonne am nächsten?', 'Merkur', 'Venus', 'Mars', 'Erde', null),
  ('Wissenschaft & Technik', 'Wie viele Knochen hat ein erwachsener Mensch?', '206', '186', '226', '256', null),
  ('Wissenschaft & Technik', 'Wer entwickelte die Relativitätstheorie?', 'Albert Einstein', 'Isaac Newton', 'Max Planck', 'Niels Bohr', null),
  ('Wissenschaft & Technik', 'Was misst man in Hertz?', 'Frequenz', 'Stromstärke', 'Leistung', 'Druck', null),
  ('Wissenschaft & Technik', 'Wer gilt als Erfinder des World Wide Web?', 'Tim Berners-Lee', 'Bill Gates', 'Steve Jobs', 'Linus Torvalds', '1989 am CERN bei Genf.'),
  ('Wissenschaft & Technik', 'Welches Gas macht den größten Teil der Erdatmosphäre aus?', 'Stickstoff', 'Sauerstoff', 'Kohlendioxid', 'Argon', 'Rund 78 Prozent.'),
  ('Wissenschaft & Technik', 'Welcher ist der größte Planet unseres Sonnensystems?', 'Jupiter', 'Saturn', 'Neptun', 'Uranus', null),
  ('Wissenschaft & Technik', 'Wie viele Chromosomen hat ein Mensch normalerweise?', '46', '23', '44', '48', '23 Paare.'),
  ('Wissenschaft & Technik', 'Welches Metall ist bei Raumtemperatur flüssig?', 'Quecksilber', 'Blei', 'Zinn', 'Natrium', null),
  ('Sport', 'Wie viele Spieler einer Fußballmannschaft stehen gleichzeitig auf dem Feld?', '11', '10', '9', '12', null),
  ('Sport', 'Wie lang ist ein Marathon?', '42,195 km', '40 km', '42,5 km', '41,195 km', null),
  ('Sport', 'In welchem Jahr wurde Deutschland zum ersten Mal Fußball-Weltmeister der Männer?', '1954', '1958', '1966', '1974', 'Das „Wunder von Bern“.'),
  ('Sport', 'In welcher Sportart gibt es ein „Birdie“?', 'Golf', 'Tennis', 'Bowling', 'Cricket', 'Ein Schlag unter Par.'),
  ('Sport', 'Wie viele Ringe hat das olympische Symbol?', '5', '4', '6', '7', null),
  ('Sport', 'Welcher Verein ist deutscher Rekordmeister im Fußball der Männer?', 'FC Bayern München', 'Borussia Dortmund', '1. FC Nürnberg', 'Hamburger SV', null),
  ('Sport', 'Wie viele Punkte zählt im Basketball ein Treffer von hinter der Dreierlinie?', '3', '2', '4', '1', null),
  ('Sport', 'Welches Tennisturnier wird auf Rasen in London gespielt?', 'Wimbledon', 'US Open', 'French Open', 'Australian Open', null),
  ('Sport', 'In welcher Sportart wird der Stanley Cup vergeben?', 'Eishockey', 'Baseball', 'American Football', 'Basketball', 'Die Trophäe der nordamerikanischen NHL.'),
  ('Sport', 'Wie lange dauert ein reguläres Handballspiel?', '60 Minuten', '70 Minuten', '80 Minuten', '90 Minuten', 'Zwei Halbzeiten à 30 Minuten.'),
  ('Film & Serien', 'Wie heißt der Zauberschüler mit der blitzförmigen Narbe?', 'Harry Potter', 'Frodo Beutlin', 'Percy Jackson', 'Ron Weasley', null),
  ('Film & Serien', 'Welcher Film gewann 1998 elf Oscars?', 'Titanic', 'Forrest Gump', 'Der Pate', 'Gladiator', null),
  ('Film & Serien', 'In welcher Serie wird ein Chemielehrer zum Drogenkoch?', 'Breaking Bad', 'Narcos', 'Ozark', 'The Wire', null),
  ('Film & Serien', 'Welcher Schauspieler spielte Captain Jack Sparrow?', 'Johnny Depp', 'Orlando Bloom', 'Brad Pitt', 'Leonardo DiCaprio', null),
  ('Film & Serien', 'In welcher Stadt spielt die Serie „Friends“?', 'New York', 'Los Angeles', 'Chicago', 'Boston', null),
  ('Film & Serien', 'In welchem Ort ermittelt Dorfpolizist Franz Eberhofer?', 'Niederkaltenkirchen', 'Dingolfing', 'Landshut', 'Bad Tölz', 'Ein erfundenes Dorf in Niederbayern.'),
  ('Film & Serien', 'Wer führte Regie bei „Jurassic Park“ (1993)?', 'Steven Spielberg', 'James Cameron', 'George Lucas', 'Ridley Scott', null),
  ('Film & Serien', 'Zu wem sagt Darth Vader „Ich bin dein Vater“?', 'Luke Skywalker', 'Han Solo', 'Obi-Wan Kenobi', 'Leia Organa', null),
  ('Film & Serien', 'Welche Pille schluckt Neo in „Matrix“?', 'Die rote', 'Die blaue', 'Die grüne', 'Die gelbe', null),
  ('Film & Serien', 'Welche deutsche Krimireihe läuft seit 1970 im Fernsehen?', 'Tatort', 'Derrick', 'Der Alte', 'Polizeiruf 110', 'Polizeiruf 110 startete 1971.'),
  ('Musik', 'Wie viele Saiten hat eine gewöhnliche Gitarre?', '6', '4', '5', '7', null),
  ('Musik', 'Aus welcher Stadt stammen die Beatles?', 'Liverpool', 'London', 'Manchester', 'Birmingham', null),
  ('Musik', 'Wer komponierte „Eine kleine Nachtmusik“?', 'Wolfgang Amadeus Mozart', 'Ludwig van Beethoven', 'Joseph Haydn', 'Johann Sebastian Bach', null),
  ('Musik', 'Wie viele Tasten hat ein klassisches Klavier?', '88', '76', '92', '96', '52 weiße und 36 schwarze.'),
  ('Musik', 'Wer wurde als „King of Pop“ bezeichnet?', 'Michael Jackson', 'Elvis Presley', 'Prince', 'Freddie Mercury', null),
  ('Musik', 'Mit welchem Lied gewann Lena 2010 den Eurovision Song Contest?', 'Satellite', 'Taken by a Stranger', 'Waterloo', 'Euphoria', null),
  ('Musik', 'Wie viele Sinfonien hat Ludwig van Beethoven vollendet?', '9', '7', '10', '12', null),
  ('Musik', 'Aus welchem Land stammt die Band ABBA?', 'Schweden', 'Norwegen', 'Dänemark', 'Finnland', null),
  ('Musik', 'Welches Blechblasinstrument hat einen Zug statt Ventilen?', 'Posaune', 'Trompete', 'Tuba', 'Waldhorn', null),
  ('Musik', 'Wer war der Sänger der Band Queen?', 'Freddie Mercury', 'Brian May', 'Roger Taylor', 'John Deacon', null),
  ('Essen & Trinken', 'Aus welcher Stadt stammt die Pizza ursprünglich?', 'Neapel', 'Rom', 'Mailand', 'Venedig', null),
  ('Essen & Trinken', 'Welche Zutaten erlaubte das bayerische Reinheitsgebot von 1516?', 'Gerste, Hopfen, Wasser', 'Gerste, Hopfen, Wasser, Hefe', 'Weizen, Hopfen, Wasser', 'Malz, Hopfen, Zucker', 'Hefe wird nicht genannt, ihre Rolle beim Brauen war damals noch unbekannt.'),
  ('Essen & Trinken', 'Woraus wird Tofu hergestellt?', 'Sojabohnen', 'Reis', 'Kichererbsen', 'Linsen', null),
  ('Essen & Trinken', 'Welche Wurst isst man traditionell nur vor dem Mittagsläuten?', 'Weißwurst', 'Leberkäse', 'Bratwurst', 'Wiener', null),
  ('Essen & Trinken', 'Aus welchem Land stammt der Gouda?', 'Niederlande', 'Belgien', 'Dänemark', 'Schweiz', null),
  ('Essen & Trinken', 'Wie heißt die scharfe grüne Paste, die oft zu Sushi gereicht wird?', 'Wasabi', 'Ingwer', 'Miso', 'Nori', null),
  ('Essen & Trinken', 'Welches Gewürz ist nach Gewicht das teuerste der Welt?', 'Safran', 'Vanille', 'Kardamom', 'Zimt', 'Für ein Kilo braucht man über 100.000 Krokusblüten.'),
  ('Essen & Trinken', 'Aus welcher Pflanze wird Tequila hergestellt?', 'Agave', 'Zuckerrohr', 'Kartoffel', 'Kaktusfeige', null),
  ('Essen & Trinken', 'Was ist ein „Obatzda“?', 'Ein Käseaufstrich', 'Eine Mehlspeise', 'Ein Schmorgericht', 'Ein Starkbier', null),
  ('Essen & Trinken', 'Welche Frucht hat eine harte, behaarte Schale und wächst an Palmen?', 'Kokosnuss', 'Ananas', 'Mango', 'Avocado', null),
  ('Kunst & Literatur', 'Wer malte die „Mona Lisa“?', 'Leonardo da Vinci', 'Michelangelo', 'Raffael', 'Sandro Botticelli', null),
  ('Kunst & Literatur', 'Wer schrieb „Faust“?', 'Johann Wolfgang von Goethe', 'Friedrich Schiller', 'Heinrich Heine', 'Thomas Mann', null),
  ('Kunst & Literatur', 'Welcher Maler schnitt sich 1888 einen Teil seines Ohrs ab?', 'Vincent van Gogh', 'Paul Gauguin', 'Claude Monet', 'Edvard Munch', null),
  ('Kunst & Literatur', 'Wer schrieb „Romeo und Julia“?', 'William Shakespeare', 'Charles Dickens', 'Oscar Wilde', 'Christopher Marlowe', null),
  ('Kunst & Literatur', 'Welchen Detektiv erfand Arthur Conan Doyle?', 'Sherlock Holmes', 'Hercule Poirot', 'Miss Marple', 'Philip Marlowe', null),
  ('Kunst & Literatur', 'Wer bemalte die Decke der Sixtinischen Kapelle?', 'Michelangelo', 'Leonardo da Vinci', 'Raffael', 'Tizian', null),
  ('Kunst & Literatur', 'In welcher Stadt steht der Louvre?', 'Paris', 'London', 'Madrid', 'Rom', null),
  ('Kunst & Literatur', 'Wer schrieb „Die Verwandlung“, in der Gregor Samsa als Ungeziefer erwacht?', 'Franz Kafka', 'Hermann Hesse', 'Thomas Mann', 'Bertolt Brecht', null),
  ('Kunst & Literatur', 'Welche Brüder sammelten Märchen wie „Hänsel und Gretel“?', 'Brüder Grimm', 'Brüder Mann', 'Brüder Lumière', 'Brüder Humboldt', null),
  ('Kunst & Literatur', 'Welcher Künstler ist für seine zerfließenden Uhren bekannt?', 'Salvador Dalí', 'Pablo Picasso', 'René Magritte', 'Joan Miró', null)
  ) as v(category, text, correct, w1, w2, w3, expl)
  join public.categories c on c.name = v.category
 where not exists (select 1 from public.questions q where q.text = v.text);
