-- =====================================================================
-- Obmanns Kinder – Grundschema
-- Tabellen, Sicherheit (RLS), Storage und alle Spielfunktionen.
-- Wird per GitHub Action mit `supabase db push` eingespielt
-- oder einmalig im Supabase SQL-Editor ausgeführt.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Profile
-- ---------------------------------------------------------------------
create table public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  username     text not null unique check (username ~ '^[a-z0-9._-]{2,24}$'),
  display_name text not null check (char_length(display_name) between 1 and 30),
  avatar_path  text,
  is_admin     boolean not null default false,
  created_at   timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
  select coalesce((select is_admin from public.profiles where id = auth.uid()), false)
$$;

-- Legt beim Anlegen eines Auth-Users automatisch das Profil an.
create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  v_username text;
begin
  v_username := lower(coalesce(nullif(new.raw_user_meta_data->>'username', ''), split_part(new.email, '@', 1)));
  insert into public.profiles (id, username, display_name)
  values (new.id, v_username, coalesce(nullif(new.raw_user_meta_data->>'display_name', ''), v_username));
  return new;
end
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------
-- Kategorien
-- ---------------------------------------------------------------------
create table public.categories (
  id         smallint generated by default as identity primary key,
  name       text not null unique check (char_length(name) between 2 and 40),
  icon       text not null default '❓',
  sort_order smallint not null default 0
);

insert into public.categories (name, icon, sort_order) values
  ('Allgemeinwissen',        '💡', 1),
  ('Geschichte',             '🏛️', 2),
  ('Geografie',              '🌍', 3),
  ('Natur & Tiere',          '🌳', 4),
  ('Wissenschaft & Technik', '🔬', 5),
  ('Sport',                  '⚽', 6),
  ('Film & Serien',          '🎬', 7),
  ('Musik',                  '🎵', 8),
  ('Essen & Trinken',        '🥨', 9),
  ('Kunst & Literatur',      '🎨', 10);

-- ---------------------------------------------------------------------
-- Fragen
-- ---------------------------------------------------------------------
create table public.questions (
  id          bigint generated always as identity primary key,
  category_id smallint not null references public.categories(id),
  author_id   uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  text        text not null check (char_length(text) between 5 and 300),
  image_path  text,
  correct     text not null check (char_length(correct) between 1 and 120),
  wrong_1     text not null check (char_length(wrong_1) between 1 and 120),
  wrong_2     text not null check (char_length(wrong_2) between 1 and 120),
  wrong_3     text not null check (char_length(wrong_3) between 1 and 120),
  explanation text check (char_length(explanation) <= 500),
  source_url  text check (source_url ~* '^https?://'),
  is_active   boolean not null default true,
  deleted_at  timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint answers_distinct check (
    lower(trim(correct)) not in (lower(trim(wrong_1)), lower(trim(wrong_2)), lower(trim(wrong_3)))
    and lower(trim(wrong_1)) not in (lower(trim(wrong_2)), lower(trim(wrong_3)))
    and lower(trim(wrong_2)) <> lower(trim(wrong_3))
  )
);
create index questions_category_idx on public.questions (category_id) where is_active and deleted_at is null;
create index questions_author_idx on public.questions (author_id);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end
$$;

create trigger questions_touch before update on public.questions
  for each row execute function public.touch_updated_at();

create table public.question_votes (
  question_id bigint not null references public.questions(id) on delete cascade,
  user_id     uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  vote        smallint not null check (vote in (-1, 1)),
  created_at  timestamptz not null default now(),
  primary key (question_id, user_id)
);

create table public.question_reports (
  id          bigint generated always as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  user_id     uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  reason      text not null check (reason in ('falsch', 'doppelt', 'unpassend', 'sonstiges')),
  comment     text check (char_length(comment) <= 300),
  status      text not null default 'offen' check (status in ('offen', 'erledigt')),
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Spiele
-- ---------------------------------------------------------------------
create table public.games (
  id          bigint generated always as identity primary key,
  mode        text not null check (mode in ('solo', 'duel', 'challenge')),
  category_id smallint references public.categories(id),
  created_by  uuid not null references public.profiles(id) on delete cascade,
  status      text not null default 'open' check (status in ('open', 'finished', 'closed')),
  created_at  timestamptz not null default now(),
  finished_at timestamptz
);
create index games_finished_idx on public.games (finished_at) where status in ('finished', 'closed');

create table public.game_questions (
  game_id      bigint not null references public.games(id) on delete cascade,
  position     smallint not null check (position between 1 and 5),
  question_id  bigint not null references public.questions(id),
  -- Reihenfolge der Antworten auf dem Bildschirm: 0 = richtig, 1–3 = falsch
  answer_order smallint[] not null,
  primary key (game_id, position)
);
create index game_questions_question_idx on public.game_questions (question_id);

create table public.game_players (
  game_id       bigint not null references public.games(id) on delete cascade,
  user_id       uuid not null references public.profiles(id) on delete cascade,
  status        text not null default 'pending' check (status in ('pending', 'done')),
  score         smallint not null default 0,
  total_ms      integer not null default 0,
  joker_used    boolean not null default false,
  finished_at   timestamptz,
  last_nudge_at timestamptz,
  primary key (game_id, user_id)
);
create index game_players_user_idx on public.game_players (user_id);

-- Pro Spieler die tatsächlich gestellte Frage. Normalerweise die Frage aus game_questions;
-- hat der Spieler diese selbst geschrieben, bekommt er eine Ersatzfrage aus derselben Kategorie.
create table public.answers (
  game_id      bigint not null,
  user_id      uuid not null,
  position     smallint not null check (position between 1 and 5),
  question_id  bigint not null references public.questions(id),
  answer_order smallint[] not null,
  chosen      smallint check (chosen between 0 and 3),   -- Index auf dem Bildschirm, null = Zeit abgelaufen
  is_correct  boolean,
  ms          integer,
  joker       boolean not null default false,
  hidden      smallint[],                               -- vom 50:50-Joker ausgeblendete Antworten
  shown_at    timestamptz not null default now(),
  answered_at timestamptz,
  primary key (game_id, user_id, position),
  foreign key (game_id, user_id) references public.game_players (game_id, user_id) on delete cascade
);
create index answers_question_idx on public.answers (question_id);

create or replace function public.is_game_player(p_game_id bigint)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (select 1 from public.game_players where game_id = p_game_id and user_id = auth.uid())
$$;

-- ---------------------------------------------------------------------
-- Unnützes Wissen
-- ---------------------------------------------------------------------
create table public.facts (
  id         bigint generated always as identity primary key,
  author_id  uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  text       text check (char_length(text) <= 1000),
  image_path text,
  created_at timestamptz not null default now(),
  constraint fact_not_empty check (nullif(trim(coalesce(text, '')), '') is not null or image_path is not null)
);
create index facts_created_idx on public.facts (created_at desc);

create table public.fact_likes (
  fact_id    bigint not null references public.facts(id) on delete cascade,
  user_id    uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (fact_id, user_id)
);

-- ---------------------------------------------------------------------
-- Push, Monatswertung, interne Konfiguration
-- ---------------------------------------------------------------------
create table public.push_subscriptions (
  id         bigint generated always as identity primary key,
  user_id    uuid not null references public.profiles(id) on delete cascade,
  endpoint   text not null unique,
  p256dh     text not null,
  auth       text not null,
  created_at timestamptz not null default now()
);

create table public.monthly_results (
  month   date not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  points  integer not null,
  wins    integer not null,
  games   integer not null,
  rank    integer not null,
  primary key (month, user_id)
);

-- Nur für die Datenbank selbst lesbar (z. B. push_url, push_secret).
create table public.app_config (
  key   text primary key,
  value text not null
);

-- =====================================================================
-- Row Level Security
-- =====================================================================
alter table public.profiles           enable row level security;
alter table public.categories         enable row level security;
alter table public.questions          enable row level security;
alter table public.question_votes     enable row level security;
alter table public.question_reports   enable row level security;
alter table public.games              enable row level security;
alter table public.game_questions     enable row level security;
alter table public.game_players       enable row level security;
alter table public.answers            enable row level security;
alter table public.facts              enable row level security;
alter table public.fact_likes         enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.monthly_results    enable row level security;
alter table public.app_config         enable row level security;

-- Profile: alle sehen alle, jeder ändert nur seinen Anzeigenamen/Avatar
create policy "Profile lesen" on public.profiles for select to authenticated using (true);
create policy "Eigenes Profil ändern" on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

-- Kategorien: alle lesen, nur Admin ändert
create policy "Kategorien lesen" on public.categories for select to authenticated using (true);
create policy "Kategorien verwalten" on public.categories for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Fragen: direkt lesbar nur für Autor und Admin (sonst wäre die Lösung sichtbar).
-- Gespielt wird ausschließlich über die Funktionen weiter unten.
create policy "Eigene Fragen lesen" on public.questions for select to authenticated
  using (author_id = auth.uid() or public.is_admin());
create policy "Fragen anlegen" on public.questions for insert to authenticated
  with check (author_id = auth.uid());
create policy "Eigene Fragen ändern" on public.questions for update to authenticated
  using (author_id = auth.uid() or public.is_admin())
  with check (author_id = auth.uid() or public.is_admin());

-- Bewertungen
create policy "Bewertungen lesen" on public.question_votes for select to authenticated using (true);
create policy "Eigene Bewertung" on public.question_votes for insert to authenticated with check (user_id = auth.uid());
create policy "Eigene Bewertung ändern" on public.question_votes for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Eigene Bewertung löschen" on public.question_votes for delete to authenticated using (user_id = auth.uid());

-- Meldungen
create policy "Meldungen lesen" on public.question_reports for select to authenticated
  using (user_id = auth.uid() or public.is_admin());
create policy "Melden" on public.question_reports for insert to authenticated with check (user_id = auth.uid());
create policy "Meldungen bearbeiten" on public.question_reports for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Spiele: nur Teilnehmer lesen, Schreiben nur über Funktionen
create policy "Eigene Spiele" on public.games for select to authenticated using (public.is_game_player(id));
create policy "Eigene Spielfragen" on public.game_questions for select to authenticated using (public.is_game_player(game_id));
create policy "Mitspieler" on public.game_players for select to authenticated using (public.is_game_player(game_id));
create policy "Eigene Antworten" on public.answers for select to authenticated using (user_id = auth.uid());

-- Unnützes Wissen
create policy "Fakten lesen" on public.facts for select to authenticated using (true);
create policy "Fakten posten" on public.facts for insert to authenticated with check (author_id = auth.uid());
create policy "Eigene Fakten löschen" on public.facts for delete to authenticated
  using (author_id = auth.uid() or public.is_admin());
create policy "Likes lesen" on public.fact_likes for select to authenticated using (true);
create policy "Liken" on public.fact_likes for insert to authenticated with check (user_id = auth.uid());
create policy "Like entfernen" on public.fact_likes for delete to authenticated using (user_id = auth.uid());

-- Push-Abos: nur eigene sehen
create policy "Eigene Push-Abos" on public.push_subscriptions for select to authenticated using (user_id = auth.uid());

-- Monatswertung: alle lesen
create policy "Monatswertung lesen" on public.monthly_results for select to authenticated using (true);

-- app_config: keine Policy = für Clients unsichtbar

-- =====================================================================
-- Rechte (Supabase vergibt standardmäßig zu viel)
-- =====================================================================
revoke all on all tables in schema public from anon, authenticated;

grant select on public.profiles to authenticated;
grant update (display_name, avatar_path) on public.profiles to authenticated;
grant select, insert, update, delete on public.categories to authenticated;
grant select, insert on public.questions to authenticated;
grant update (category_id, text, image_path, correct, wrong_1, wrong_2, wrong_3, explanation, source_url, is_active)
  on public.questions to authenticated;
grant select, insert, update, delete on public.question_votes to authenticated;
grant select, insert, update on public.question_reports to authenticated;
grant select on public.games, public.game_questions, public.game_players, public.answers to authenticated;
grant select, insert, delete on public.facts, public.fact_likes to authenticated;
grant select on public.push_subscriptions to authenticated;
grant select on public.monthly_results to authenticated;
grant usage on all sequences in schema public to authenticated;

-- =====================================================================
-- Storage: Bilder für Fragen und Posts
-- =====================================================================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values
  ('question-images', 'question-images', false, 3145728, array['image/webp', 'image/jpeg', 'image/png', 'image/gif']),
  ('fact-images',     'fact-images',     false, 3145728, array['image/webp', 'image/jpeg', 'image/png', 'image/gif'])
on conflict (id) do nothing;

create policy "Bilder lesen" on storage.objects for select to authenticated
  using (bucket_id in ('question-images', 'fact-images'));
create policy "Eigene Bilder hochladen" on storage.objects for insert to authenticated
  with check (bucket_id in ('question-images', 'fact-images') and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Eigene Bilder löschen" on storage.objects for delete to authenticated
  using (bucket_id in ('question-images', 'fact-images') and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin()));

-- =====================================================================
-- Push auslösen (über pg_net an die Edge Function "push")
-- =====================================================================
create or replace function public.send_push(p_user_ids uuid[], p_title text, p_body text, p_url text default '/')
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_url    text;
  v_secret text;
begin
  if p_user_ids is null or cardinality(p_user_ids) = 0 then
    return;
  end if;
  select value into v_url from public.app_config where key = 'push_url';
  select value into v_secret from public.app_config where key = 'push_secret';
  if v_url is null or v_secret is null then
    return; -- Push noch nicht eingerichtet
  end if;
  begin
    perform net.http_post(
      url     := v_url,
      body    := jsonb_build_object('user_ids', to_jsonb(p_user_ids), 'title', p_title, 'body', p_body, 'url', p_url),
      headers := jsonb_build_object('Content-Type', 'application/json', 'x-push-secret', v_secret)
    );
  exception when others then
    raise warning 'Push konnte nicht ausgelöst werden: %', sqlerrm;
  end;
end
$$;

-- =====================================================================
-- Spiellogik
-- =====================================================================

-- Wählt Fragen aus: keine Fragen der ausgeschlossenen Autoren, für die Spieler
-- ungesehene zuerst, schlecht bewertete zuletzt. Ohne Kategorie: pro Kategorie
-- die beste Frage, damit möglichst 5 verschiedene Kategorien drankommen.
create or replace function public._pick_questions(
  p_seen_by uuid[], p_exclude_authors uuid[], p_category smallint, p_count int, p_exclude_ids bigint[] default '{}')
returns table (question_id bigint)
language sql volatile security definer set search_path = public
as $$
  with eligible as (
    select q.id,
           q.category_id,
           (select max(a.shown_at) from public.answers a
             where a.question_id = q.id and a.user_id = any (p_seen_by)) as last_seen,
           coalesce((select sum(v.vote) from public.question_votes v where v.question_id = q.id), 0) as votes,
           random() as r
      from public.questions q
     where q.is_active
       and q.deleted_at is null
       and q.author_id <> all (coalesce(p_exclude_authors, '{}'))
       and q.id <> all (coalesce(p_exclude_ids, '{}'))
       and (p_category is null or q.category_id = p_category)
  ),
  ranked as (
    select e.*,
           row_number() over (
             partition by e.category_id
             order by (e.last_seen is not null), (e.votes <= -3), e.last_seen nulls first, e.r
           ) as rn
      from eligible e
  )
  select id
    from ranked
   order by rn, (last_seen is not null), (votes <= -3), r
   limit p_count
$$;

create or replace function public._shuffled_order()
returns smallint[]
language sql volatile
as $$
  select array_agg(x order by random()) from unnest('{0,1,2,3}'::smallint[]) as x
$$;

-- Neues Spiel anlegen: 'solo' (mit Kategorie), 'duel' (1 Gegner), 'challenge' (mehrere)
create or replace function public.create_game(p_mode text, p_category_id smallint default null, p_invitees uuid[] default '{}')
returns bigint
language plpgsql security definer set search_path = public
as $$
declare
  v_me      uuid := auth.uid();
  v_players uuid[];
  v_game    bigint;
  v_ids     bigint[];
  v_name    text;
begin
  if v_me is null then
    raise exception 'Nicht angemeldet';
  end if;

  p_invitees := coalesce(array(select distinct u from unnest(coalesce(p_invitees, '{}')) u where u <> v_me), '{}');

  if p_mode = 'solo' then
    if p_category_id is null then
      raise exception 'Bitte wähle eine Kategorie.';
    end if;
    p_invitees := '{}';
  elsif p_mode = 'duel' then
    if cardinality(p_invitees) <> 1 then
      raise exception 'Ein Duell braucht genau einen Gegner.';
    end if;
    p_category_id := null;
  elsif p_mode = 'challenge' then
    if cardinality(p_invitees) < 1 then
      raise exception 'Wähle mindestens eine Person für die Challenge.';
    end if;
    p_category_id := null;
  else
    raise exception 'Unbekannter Spielmodus: %', p_mode;
  end if;

  if (select count(*) from public.profiles where id = any (p_invitees)) <> cardinality(p_invitees) then
    raise exception 'Mindestens ein Mitspieler existiert nicht.';
  end if;

  v_players := array[v_me] || p_invitees;

  -- Zuerst Fragen, die keiner der Mitspieler geschrieben hat
  v_ids := array(select question_id from public._pick_questions(v_players, v_players, p_category_id, 5));
  -- Reicht das nicht (z. B. Challenge mit allen), dürfen auch Fragen von Mitspielern dran;
  -- deren Autor bekommt an dieser Stelle später eine Ersatzfrage.
  if p_mode <> 'solo' and cardinality(v_ids) < 5 then
    v_ids := v_ids || array(select question_id from public._pick_questions(v_players, '{}', null, 5 - cardinality(v_ids), v_ids));
  end if;
  if cardinality(v_ids) < 5 then
    raise exception 'Es gibt nur % passende Fragen, für ein Spiel braucht es 5. Ladet mehr Fragen hoch!', cardinality(v_ids);
  end if;

  insert into public.games (mode, category_id, created_by)
  values (p_mode, p_category_id, v_me)
  returning id into v_game;

  insert into public.game_questions (game_id, position, question_id, answer_order)
  select v_game, (row_number() over (order by random()))::smallint, id, public._shuffled_order()
    from unnest(v_ids) as id;

  insert into public.game_players (game_id, user_id)
  select v_game, unnest(v_players);

  if p_mode = 'challenge' then
    select display_name into v_name from public.profiles where id = v_me;
    perform public.send_push(p_invitees, 'Neue Gruppen-Challenge',
      v_name || ' fordert dich heraus. 5 Fragen warten auf dich.', '/#/spiel/' || v_game);
  end if;

  return v_game;
end
$$;

-- Wertet ein Spiel aus: Rang je Spieler und Punkte für die Rangliste
create or replace function public._game_ranks(p_from timestamptz default null, p_to timestamptz default null)
returns table (game_id bigint, mode text, finished_at timestamptz, user_id uuid, score smallint, total_ms integer, rnk bigint, points integer)
language sql stable security definer set search_path = public
as $$
  with done as (
    select g.id as game_id, g.mode, g.finished_at, gp.user_id, gp.score, gp.total_ms,
           rank() over (partition by g.id order by gp.score desc, gp.total_ms asc) as rnk,
           count(*) over (partition by g.id) as n_done
      from public.games g
      join public.game_players gp on gp.game_id = g.id and gp.status = 'done'
     where g.mode in ('duel', 'challenge')
       and g.status in ('finished', 'closed')
       and (p_from is null or g.finished_at >= p_from)
       and (p_to is null or g.finished_at < p_to)
  ),
  tied as (
    select d.*, count(*) over (partition by d.game_id, d.rnk) as n_same
      from done d
  )
  select game_id, mode, finished_at, user_id, score, total_ms, rnk,
         case
           when n_done < 2 then 0
           when mode = 'duel' and rnk = 1 and n_same = 1 then 3
           when mode = 'duel' and rnk = 1 then 1
           when mode = 'challenge' and rnk = 1 then 3
           when mode = 'challenge' and rnk = 2 then 2
           when mode = 'challenge' and rnk = 3 then 1
           else 0
         end::integer as points
    from tied
$$;

-- Spieler hat alle 5 Fragen beantwortet
create or replace function public._finish_player(p_game_id bigint, p_user uuid)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_game    public.games;
  v_name    text;
  v_pending int;
  r         record;
  v_total   int;
  v_text    text;
begin
  update public.game_players gp
     set status = 'done',
         finished_at = now(),
         score = (select count(*) from public.answers a where a.game_id = p_game_id and a.user_id = p_user and a.is_correct),
         total_ms = (select coalesce(sum(a.ms), 0) from public.answers a where a.game_id = p_game_id and a.user_id = p_user)
   where gp.game_id = p_game_id and gp.user_id = p_user;

  select * into v_game from public.games where id = p_game_id;
  select display_name into v_name from public.profiles where id = p_user;
  select count(*) into v_pending from public.game_players where game_id = p_game_id and status = 'pending';

  if v_game.mode = 'solo' then
    update public.games set status = 'finished', finished_at = now() where id = p_game_id;
    return;
  end if;

  -- Duell: Herausforderer ist fertig → Gegner bekommt die Herausforderung
  if v_game.mode = 'duel' and p_user = v_game.created_by and v_pending > 0 then
    perform public.send_push(
      array(select user_id from public.game_players where game_id = p_game_id and user_id <> p_user),
      'Neues Duell', v_name || ' hat dich zum Duell herausgefordert.', '/#/spiel/' || p_game_id);
  end if;

  if v_pending = 0 then
    update public.games set status = 'finished', finished_at = now() where id = p_game_id and status = 'open';
    select count(*) into v_total from public.game_players where game_id = p_game_id;
    for r in
      select gr.user_id, gr.rnk, gr.score from public._game_ranks() gr where gr.game_id = p_game_id
    loop
      if r.user_id = p_user then
        continue; -- sieht das Ergebnis ohnehin gerade
      end if;
      if v_game.mode = 'duel' then
        v_text := case when r.rnk = 1 then 'Gewonnen! ' else 'Verloren. ' end
                  || 'Du hattest ' || r.score || ' von 5 richtig.';
        perform public.send_push(array[r.user_id], 'Duell gegen ' || v_name || ' ist fertig', v_text, '/#/spiel/' || p_game_id);
      else
        perform public.send_push(array[r.user_id], 'Gruppen-Challenge ist fertig',
          'Du bist auf Platz ' || r.rnk || ' von ' || v_total || '.', '/#/spiel/' || p_game_id);
      end if;
    end loop;
  end if;
end
$$;

-- Speichert eine Antwort (p_choice null = Zeit abgelaufen)
create or replace function public._record_answer(p_game_id bigint, p_user uuid, p_position smallint, p_choice smallint)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_ans     public.answers;
  v_q       public.questions;
  v_correct smallint;
  v_ms      int;
  v_ok      boolean;
begin
  select * into v_ans from public.answers
   where game_id = p_game_id and user_id = p_user and position = p_position
   for update;
  if not found or v_ans.answered_at is not null then
    raise exception 'Diese Frage ist nicht offen.';
  end if;

  select * into v_q from public.questions where id = v_ans.question_id;

  v_correct := (array_position(v_ans.answer_order, 0::smallint) - 1)::smallint;
  v_ms := least(30000, (extract(epoch from (now() - v_ans.shown_at)) * 1000)::int);

  -- 30 Sekunden + 2 Sekunden Toleranz für das Netz
  if p_choice is null or now() - v_ans.shown_at > interval '32 seconds' then
    p_choice := null;
    v_ms := 30000;
  end if;
  if p_choice is not null and v_ans.hidden is not null and p_choice = any (v_ans.hidden) then
    raise exception 'Diese Antwort wurde vom Joker ausgeblendet.';
  end if;
  v_ok := p_choice is not null and p_choice = v_correct;

  update public.answers
     set chosen = p_choice, is_correct = v_ok, ms = v_ms, answered_at = now()
   where game_id = p_game_id and user_id = p_user and position = p_position;

  if p_position = 5 then
    perform public._finish_player(p_game_id, p_user);
  end if;

  return jsonb_build_object(
    'position', p_position,
    'chosen', p_choice,
    'correct_index', v_correct,
    'is_correct', v_ok,
    'timed_out', p_choice is null,
    'explanation', v_q.explanation,
    'source_url', v_q.source_url,
    'question_id', v_q.id,
    'author', (select display_name from public.profiles where id = v_q.author_id),
    'my_vote', (select vote from public.question_votes where question_id = v_q.id and user_id = p_user),
    'finished', p_position = 5
  );
end
$$;

-- Liefert die aktuelle Frage (ohne Lösung). Startet die 30 Sekunden.
create or replace function public.next_question(p_game_id bigint)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_me     uuid := auth.uid();
  v_game   public.games;
  v_player public.game_players;
  v_ans    public.answers;
  v_pos    smallint;
  v_gq     public.game_questions;
  v_q      public.questions;
  v_order  smallint[];
  v_sub    bigint;
begin
  select * into v_game from public.games where id = p_game_id;
  if not found then
    raise exception 'Spiel nicht gefunden.';
  end if;

  select * into v_player from public.game_players
   where game_id = p_game_id and user_id = v_me
   for update;
  if not found then
    raise exception 'Du spielst in diesem Spiel nicht mit.';
  end if;
  if v_player.status = 'done' then
    return jsonb_build_object('done', true);
  end if;
  if v_game.status = 'closed' then
    raise exception 'Diese Challenge wurde schon geschlossen.';
  end if;
  if v_game.mode = 'duel' and v_game.created_by <> v_me and exists (
       select 1 from public.game_players
        where game_id = p_game_id and user_id = v_game.created_by and status <> 'done') then
    raise exception 'Dein Gegner spielt seine Fragen noch. Du bekommst einen Push, sobald du dran bist.';
  end if;

  -- Gibt es eine angezeigte, aber noch nicht beantwortete Frage?
  select * into v_ans from public.answers
   where game_id = p_game_id and user_id = v_me and answered_at is null;
  if found then
    if now() - v_ans.shown_at > interval '32 seconds' then
      perform public._record_answer(p_game_id, v_me, v_ans.position, null);
      if v_ans.position = 5 then
        return jsonb_build_object('done', true);
      end if;
    else
      v_pos := v_ans.position;
    end if;
  end if;

  if v_pos is null then
    select (coalesce(max(position), 0) + 1)::smallint into v_pos
      from public.answers where game_id = p_game_id and user_id = v_me;
    if v_pos > 5 then
      return jsonb_build_object('done', true);
    end if;

    select * into v_gq from public.game_questions where game_id = p_game_id and position = v_pos;
    select * into v_q from public.questions where id = v_gq.question_id;
    v_order := v_gq.answer_order;

    -- Eigene Frage? Dann Ersatzfrage aus derselben Kategorie (notfalls aus einer anderen)
    if v_q.author_id = v_me then
      select question_id into v_sub
        from public._pick_questions(array[v_me], array[v_me], v_q.category_id, 1,
               array(select question_id from public.game_questions where game_id = p_game_id)
               || array(select question_id from public.answers where game_id = p_game_id));
      if v_sub is null then
        select question_id into v_sub
          from public._pick_questions(array[v_me], array[v_me], null, 1,
                 array(select question_id from public.game_questions where game_id = p_game_id)
                 || array(select question_id from public.answers where game_id = p_game_id));
      end if;
      if v_sub is null then
        raise exception 'Für deine eigene Frage gibt es keine Ersatzfrage. Ladet mehr Fragen hoch!';
      end if;
      select * into v_q from public.questions where id = v_sub;
      v_order := public._shuffled_order();
    end if;

    insert into public.answers (game_id, user_id, position, question_id, answer_order)
    values (p_game_id, v_me, v_pos, v_q.id, v_order)
    returning * into v_ans;
  end if;

  select * into v_q from public.questions where id = v_ans.question_id;
  select * into v_gq from public.game_questions where game_id = p_game_id and position = v_pos;

  return jsonb_build_object(
    'done', false,
    'position', v_pos,
    'total', 5,
    'question_id', v_q.id,
    'text', v_q.text,
    'image_path', v_q.image_path,
    'category', (select jsonb_build_object('name', c.name, 'icon', c.icon) from public.categories c where c.id = v_q.category_id),
    'author', (select display_name from public.profiles where id = v_q.author_id),
    'substitute', v_ans.question_id <> v_gq.question_id,
    'options', (
      select jsonb_agg(case o when 0 then v_q.correct when 1 then v_q.wrong_1 when 2 then v_q.wrong_2 else v_q.wrong_3 end order by ord)
        from unnest(v_ans.answer_order) with ordinality as t(o, ord)
    ),
    'seconds_left', greatest(0, 30 - extract(epoch from (now() - v_ans.shown_at))),
    'joker_available', not v_player.joker_used,
    'hidden', coalesce(to_jsonb(v_ans.hidden), '[]'::jsonb)
  );
end
$$;

create or replace function public.submit_answer(p_game_id bigint, p_position smallint, p_choice smallint)
returns jsonb
language plpgsql security definer set search_path = public
as $$
begin
  if not exists (select 1 from public.game_players where game_id = p_game_id and user_id = auth.uid() and status = 'pending') then
    raise exception 'Du kannst in diesem Spiel nicht (mehr) antworten.';
  end if;
  return public._record_answer(p_game_id, auth.uid(), p_position, p_choice);
end
$$;

-- 50:50-Joker: liefert die zwei ausgeblendeten falschen Antworten
create or replace function public.use_joker(p_game_id bigint, p_position smallint)
returns smallint[]
language plpgsql security definer set search_path = public
as $$
declare
  v_me     uuid := auth.uid();
  v_player public.game_players;
  v_ans    public.answers;
  v_hidden smallint[];
begin
  select * into v_player from public.game_players where game_id = p_game_id and user_id = v_me for update;
  if not found or v_player.status <> 'pending' then
    raise exception 'Du kannst in diesem Spiel keinen Joker setzen.';
  end if;
  if v_player.joker_used then
    raise exception 'Dein Joker ist für dieses Spiel schon verbraucht.';
  end if;

  select * into v_ans from public.answers
   where game_id = p_game_id and user_id = v_me and position = p_position and answered_at is null;
  if not found or now() - v_ans.shown_at > interval '30 seconds' then
    raise exception 'Die Frage ist nicht mehr offen.';
  end if;

  select array_agg(i order by i) into v_hidden
    from (select (ord - 1)::smallint as i
            from unnest(v_ans.answer_order) with ordinality as t(o, ord)
           where o <> 0
           order by random()
           limit 2) s;

  update public.answers set joker = true, hidden = v_hidden
   where game_id = p_game_id and user_id = v_me and position = p_position;
  update public.game_players set joker_used = true where game_id = p_game_id and user_id = v_me;

  return v_hidden;
end
$$;

-- Anstupsen: höchstens einmal pro Tag
create or replace function public.nudge(p_game_id bigint)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_me      uuid := auth.uid();
  v_player  public.game_players;
  v_game    public.games;
  v_pending uuid[];
  v_name    text;
begin
  select * into v_game from public.games where id = p_game_id;
  select * into v_player from public.game_players where game_id = p_game_id and user_id = v_me for update;
  if not found or v_game.status <> 'open' then
    raise exception 'Dieses Spiel ist nicht mehr offen.';
  end if;
  if v_player.status <> 'done' then
    raise exception 'Spiel erst deine eigenen Fragen.';
  end if;
  if v_player.last_nudge_at is not null and v_player.last_nudge_at > now() - interval '20 hours' then
    raise exception 'Du hast heute schon angestupst. Morgen geht es wieder.';
  end if;

  select array_agg(user_id) into v_pending from public.game_players where game_id = p_game_id and status = 'pending';
  if v_pending is null then
    raise exception 'Alle haben schon gespielt.';
  end if;

  update public.game_players set last_nudge_at = now() where game_id = p_game_id and user_id = v_me;
  select display_name into v_name from public.profiles where id = v_me;
  perform public.send_push(v_pending, 'Anstupser', v_name || ' wartet auf deinen Zug.', '/#/spiel/' || p_game_id);
end
$$;

-- Gruppen-Challenge schließen (Ersteller oder Admin)
create or replace function public.close_challenge(p_game_id bigint)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_game public.games;
begin
  select * into v_game from public.games where id = p_game_id for update;
  if not found or v_game.mode <> 'challenge' then
    raise exception 'Keine Gruppen-Challenge.';
  end if;
  if v_game.created_by <> auth.uid() and not public.is_admin() then
    raise exception 'Nur wer die Challenge gestartet hat, kann sie schließen.';
  end if;
  if v_game.status <> 'open' then
    raise exception 'Die Challenge ist schon beendet.';
  end if;
  update public.games set status = 'closed', finished_at = now() where id = p_game_id;
end
$$;

-- Alles für die Spielseite: Spieler, Status und (wenn man fertig ist) die Fragen mit Lösungen
create or replace function public.game_details(p_game_id bigint)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
declare
  v_me       uuid := auth.uid();
  v_game     public.games;
  v_mine     public.game_players;
  v_reveal   boolean;
  v_creator_done boolean;
begin
  select * into v_game from public.games where id = p_game_id;
  select * into v_mine from public.game_players where game_id = p_game_id and user_id = v_me;
  if v_game.id is null or v_mine.user_id is null then
    raise exception 'Spiel nicht gefunden.';
  end if;

  v_reveal := v_mine.status = 'done' or v_game.status <> 'open';
  select status = 'done' into v_creator_done from public.game_players where game_id = p_game_id and user_id = v_game.created_by;

  return jsonb_build_object(
    'id', v_game.id,
    'mode', v_game.mode,
    'status', v_game.status,
    'created_at', v_game.created_at,
    'finished_at', v_game.finished_at,
    'created_by', v_game.created_by,
    'category', (select jsonb_build_object('name', c.name, 'icon', c.icon) from public.categories c where c.id = v_game.category_id),
    'my_status', v_mine.status,
    'can_play', v_mine.status = 'pending' and v_game.status = 'open'
                and (v_game.mode <> 'duel' or v_game.created_by = v_me or v_creator_done),
    'started', exists (select 1 from public.answers where game_id = p_game_id and user_id = v_me),
    'joker_used', v_mine.joker_used,
    'can_nudge', v_mine.status = 'done' and v_game.status = 'open'
                 and (v_mine.last_nudge_at is null or v_mine.last_nudge_at <= now() - interval '20 hours')
                 and exists (select 1 from public.game_players where game_id = p_game_id and status = 'pending'),
    'can_close', v_game.mode = 'challenge' and v_game.status = 'open' and (v_game.created_by = v_me or public.is_admin()),
    'players', (
      select jsonb_agg(jsonb_build_object(
               'user_id', gp.user_id,
               'display_name', p.display_name,
               'status', gp.status,
               'score', case when v_reveal and gp.status = 'done' then gp.score end,
               'total_ms', case when v_reveal and gp.status = 'done' then gp.total_ms end,
               'rank', case when v_reveal and gp.status = 'done'
                            then (select count(*) + 1 from public.game_players o
                                   where o.game_id = gp.game_id and o.status = 'done'
                                     and (o.score > gp.score or (o.score = gp.score and o.total_ms < gp.total_ms))) end
             ) order by (gp.status = 'done') desc, gp.score desc, gp.total_ms, p.display_name)
        from public.game_players gp
        join public.profiles p on p.id = gp.user_id
       where gp.game_id = p_game_id
    ),
    -- Pro Position die Frage, die ICH bekommen habe (ggf. Ersatzfrage); Antworten der anderen
    -- nur dort, wo sie dieselbe Frage hatten.
    'questions', case when not v_reveal then '[]'::jsonb else (
      select coalesce(jsonb_agg(jsonb_build_object(
               'position', x.position,
               'question_id', q.id,
               'substitute', x.substitute,
               'text', q.text,
               'image_path', q.image_path,
               'category', jsonb_build_object('name', c.name, 'icon', c.icon),
               'author', au.display_name,
               'explanation', q.explanation,
               'source_url', q.source_url,
               'options', (select jsonb_agg(case o when 0 then q.correct when 1 then q.wrong_1 when 2 then q.wrong_2 else q.wrong_3 end order by ord)
                             from unnest(x.answer_order) with ordinality as t(o, ord)),
               'correct_index', array_position(x.answer_order, 0::smallint) - 1,
               'my_vote', (select vote from public.question_votes v where v.question_id = q.id and v.user_id = v_me),
               'answers', (
                 select coalesce(jsonb_object_agg(a.user_id, jsonb_build_object(
                          'chosen', a.chosen, 'is_correct', a.is_correct, 'ms', a.ms, 'joker', a.joker,
                          'chosen_text', case when a.chosen is null then null else
                            (case a.answer_order[a.chosen + 1] when 0 then q.correct when 1 then q.wrong_1 when 2 then q.wrong_2 else q.wrong_3 end) end
                        )), '{}'::jsonb)
                   from public.answers a
                   join public.game_players gp2 on gp2.game_id = a.game_id and gp2.user_id = a.user_id and gp2.status = 'done'
                  where a.game_id = x.game_id and a.position = x.position and a.question_id = q.id
               )
             ) order by x.position), '[]'::jsonb)
        from (
          select gq.game_id, gq.position,
                 coalesce(ma.question_id, gq.question_id) as qid,
                 coalesce(ma.answer_order, gq.answer_order) as answer_order,
                 coalesce(ma.question_id <> gq.question_id, false) as substitute
            from public.game_questions gq
            left join public.answers ma on ma.game_id = gq.game_id and ma.position = gq.position and ma.user_id = v_me
           where gq.game_id = p_game_id
        ) x
        join public.questions q on q.id = x.qid
        join public.categories c on c.id = q.category_id
        join public.profiles au on au.id = q.author_id
    ) end
  );
end
$$;

-- Übersicht für den Start-Tab
create or replace function public.my_games()
returns jsonb
language sql stable security definer set search_path = public
as $$
  select coalesce(jsonb_agg(row_to_json(x)::jsonb order by x.sort_at desc), '[]'::jsonb)
    from (
      select g.id, g.mode, g.status, g.created_at, g.finished_at, g.created_by,
             coalesce(g.finished_at, g.created_at) as sort_at,
             mine.status as my_status,
             (mine.status = 'pending' and g.status = 'open'
               and (g.mode <> 'duel' or g.created_by = auth.uid()
                    or exists (select 1 from public.game_players c where c.game_id = g.id and c.user_id = g.created_by and c.status = 'done'))) as my_turn,
             (mine.status = 'done' and g.status = 'open'
               and (mine.last_nudge_at is null or mine.last_nudge_at <= now() - interval '20 hours')) as can_nudge,
             (select jsonb_build_object('name', c.name, 'icon', c.icon) from public.categories c where c.id = g.category_id) as category,
             (select jsonb_agg(jsonb_build_object(
                       'user_id', gp.user_id,
                       'display_name', p.display_name,
                       'status', gp.status,
                       'score', case when mine.status = 'done' or g.status <> 'open' then gp.score end,
                       'total_ms', case when mine.status = 'done' or g.status <> 'open' then gp.total_ms end
                     ) order by gp.user_id = g.created_by desc, p.display_name)
                from public.game_players gp join public.profiles p on p.id = gp.user_id
               where gp.game_id = g.id) as players
        from public.games g
        join public.game_players mine on mine.game_id = g.id and mine.user_id = auth.uid()
       where (g.mode <> 'solo' or g.status = 'open')
         and (g.status = 'open' or g.finished_at > now() - interval '30 days')
       order by coalesce(g.finished_at, g.created_at) desc
       limit 60
    ) x
$$;

-- Rangliste: 'month' (aktueller oder angegebener Monat) oder 'all'
create or replace function public.leaderboard(p_period text default 'month', p_month date default null)
returns table (user_id uuid, display_name text, points integer, wins integer, games integer, correct_rate numeric)
language plpgsql stable security definer set search_path = public
as $$
declare
  v_from timestamptz;
  v_to   timestamptz;
begin
  if p_period = 'month' then
    v_from := date_trunc('month', coalesce(p_month::timestamptz, now()));
    v_to   := v_from + interval '1 month';
  end if;

  return query
  with ranks as (
    select * from public._game_ranks(v_from, v_to)
  ),
  ans as (
    select a.user_id, count(*) filter (where a.is_correct) as ok, count(*) as total
      from public.answers a
      join public.games g on g.id = a.game_id
     where a.answered_at is not null
       and g.mode <> 'solo'
       and (v_from is null or a.answered_at >= v_from)
       and (v_to is null or a.answered_at < v_to)
     group by a.user_id
  )
  select p.id,
         p.display_name,
         coalesce(sum(r.points), 0)::integer,
         coalesce(count(*) filter (where r.rnk = 1 and r.points >= 3), 0)::integer,
         coalesce(count(r.game_id), 0)::integer,
         round(coalesce(max(ans.ok)::numeric / nullif(max(ans.total), 0), 0) * 100, 0)
    from public.profiles p
    left join ranks r on r.user_id = p.id
    left join ans on ans.user_id = p.id
   group by p.id, p.display_name
   order by 3 desc, 4 desc, 6 desc, 2;
end
$$;

-- Trefferquote pro Kategorie (alle Modi)
create or replace function public.category_stats(p_user_id uuid default null)
returns table (category_id smallint, name text, icon text, answered integer, correct integer, rate numeric)
language sql stable security definer set search_path = public
as $$
  select c.id, c.name, c.icon,
         count(a.*)::integer,
         count(a.*) filter (where a.is_correct)::integer,
         round(100.0 * count(a.*) filter (where a.is_correct) / nullif(count(a.*), 0), 0)
    from public.categories c
    left join public.questions q on q.category_id = c.id
    left join public.answers a on a.question_id = q.id
                               and a.user_id = coalesce(p_user_id, auth.uid()) and a.answered_at is not null
   group by c.id, c.name, c.icon, c.sort_order
   order by c.sort_order, c.name
$$;

-- Beste Spieler je Kategorie (mind. 5 beantwortete Fragen)
create or replace function public.category_leaders()
returns table (category_id smallint, name text, icon text, user_id uuid, display_name text, answered integer, rate numeric)
language sql stable security definer set search_path = public
as $$
  with per as (
    select q.category_id, a.user_id,
           count(*) as answered,
           100.0 * count(*) filter (where a.is_correct) / count(*) as rate
      from public.answers a
      join public.questions q on q.id = a.question_id
     where a.answered_at is not null
     group by q.category_id, a.user_id
    having count(*) >= 5
  ),
  best as (
    select per.*, row_number() over (partition by per.category_id order by per.rate desc, per.answered desc) as rn
      from per
  )
  select c.id, c.name, c.icon, b.user_id, p.display_name, b.answered::integer, round(b.rate, 0)
    from public.categories c
    left join best b on b.category_id = c.id and b.rn = 1
    left join public.profiles p on p.id = b.user_id
   order by c.sort_order, c.name
$$;

-- Statistik zu den eigenen Fragen
create or replace function public.my_question_stats()
returns table (question_id bigint, plays integer, correct_rate numeric, upvotes integer, downvotes integer, open_reports integer)
language sql stable security definer set search_path = public
as $$
  select q.id,
         (select count(*) from public.answers a where a.question_id = q.id and a.answered_at is not null)::integer,
         (select round(100.0 * count(*) filter (where a.is_correct) / nullif(count(*), 0), 0)
            from public.answers a where a.question_id = q.id and a.answered_at is not null),
         (select count(*) from public.question_votes v where v.question_id = q.id and v.vote = 1)::integer,
         (select count(*) from public.question_votes v where v.question_id = q.id and v.vote = -1)::integer,
         (select count(*) from public.question_reports r where r.question_id = q.id and r.status = 'offen')::integer
    from public.questions q
   where q.author_id = auth.uid() and q.deleted_at is null
$$;

-- Wie viele aktive Fragen gibt es pro Kategorie (zeigt, wo Fragen fehlen)
create or replace function public.question_counts()
returns table (category_id smallint, name text, icon text, total integer, mine integer)
language sql stable security definer set search_path = public
as $$
  select c.id, c.name, c.icon,
         count(q.id)::integer,
         count(q.id) filter (where q.author_id = auth.uid())::integer
    from public.categories c
    left join public.questions q on q.category_id = c.id and q.is_active and q.deleted_at is null
   group by c.id, c.name, c.icon, c.sort_order
   order by c.sort_order, c.name
$$;

-- Frage löschen: schon gespielte Fragen werden nur ausgeblendet, damit alte Spiele lesbar bleiben
create or replace function public.delete_question(p_question_id bigint)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_author uuid;
begin
  select author_id into v_author from public.questions where id = p_question_id;
  if v_author is null then
    raise exception 'Frage nicht gefunden.';
  end if;
  if v_author <> auth.uid() and not public.is_admin() then
    raise exception 'Du kannst nur deine eigenen Fragen löschen.';
  end if;
  if exists (select 1 from public.game_questions where question_id = p_question_id)
     or exists (select 1 from public.answers where question_id = p_question_id) then
    update public.questions set is_active = false, deleted_at = now() where id = p_question_id;
  else
    delete from public.questions where id = p_question_id;
  end if;
end
$$;

-- Push-Abo speichern (ein Gerät gehört immer dem zuletzt angemeldeten Spieler)
create or replace function public.save_push_subscription(p_endpoint text, p_p256dh text, p_auth text)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Nicht angemeldet';
  end if;
  insert into public.push_subscriptions (user_id, endpoint, p256dh, auth)
  values (auth.uid(), p_endpoint, p_p256dh, p_auth)
  on conflict (endpoint) do update
    set user_id = excluded.user_id, p256dh = excluded.p256dh, auth = excluded.auth, created_at = now();
end
$$;

create or replace function public.delete_push_subscription(p_endpoint text)
returns void
language sql security definer set search_path = public
as $$
  delete from public.push_subscriptions where endpoint = p_endpoint and user_id = auth.uid()
$$;

-- Monatsabschluss (läuft per pg_cron am 1. jedes Monats)
create or replace function public.close_month(p_month date default null)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_month  date := coalesce(p_month, (date_trunc('month', now()) - interval '1 month')::date);
  v_label  text;
  v_winner record;
  r        record;
begin
  delete from public.monthly_results where month = v_month;

  insert into public.monthly_results (month, user_id, points, wins, games, rank)
  select v_month, l.user_id, l.points, l.wins, l.games,
         rank() over (order by l.points desc, l.wins desc)
    from public.leaderboard('month', v_month) l
   where l.games > 0;

  v_label := (array['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'])[extract(month from v_month)::int];

  select p.display_name, m.points into v_winner
    from public.monthly_results m join public.profiles p on p.id = m.user_id
   where m.month = v_month and m.rank = 1
   order by p.display_name limit 1;

  for r in
    select p.id, m.rank from public.profiles p
      left join public.monthly_results m on m.user_id = p.id and m.month = v_month
  loop
    perform public.send_push(
      array[r.id],
      'Monatswertung ' || v_label,
      case
        when v_winner.display_name is null then 'Im ' || v_label || ' wurde kein Duell gespielt. Zeit für eine Revanche!'
        when r.rank = 1 then 'Du bist Monatssieger mit ' || v_winner.points || ' Punkten!'
        when r.rank is not null then v_winner.display_name || ' gewinnt mit ' || v_winner.points || ' Punkten. Du bist auf Platz ' || r.rank || '.'
        else v_winner.display_name || ' gewinnt mit ' || v_winner.points || ' Punkten. Diesen Monat bist du wieder dabei!'
      end,
      '/#/profil');
  end loop;
end
$$;

-- Für die Keep-alive-Action (verhindert das Pausieren des Free-Projekts)
create or replace function public.keep_alive()
returns timestamptz
language sql stable
as $$
  select now()
$$;

-- =====================================================================
-- Funktionsrechte
-- =====================================================================
revoke execute on all functions in schema public from public, anon, authenticated;

grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_game_player(bigint) to authenticated;
grant execute on function public.create_game(text, smallint, uuid[]) to authenticated;
grant execute on function public.next_question(bigint) to authenticated;
grant execute on function public.submit_answer(bigint, smallint, smallint) to authenticated;
grant execute on function public.use_joker(bigint, smallint) to authenticated;
grant execute on function public.nudge(bigint) to authenticated;
grant execute on function public.close_challenge(bigint) to authenticated;
grant execute on function public.game_details(bigint) to authenticated;
grant execute on function public.my_games() to authenticated;
grant execute on function public.leaderboard(text, date) to authenticated;
grant execute on function public.category_stats(uuid) to authenticated;
grant execute on function public.category_leaders() to authenticated;
grant execute on function public.my_question_stats() to authenticated;
grant execute on function public.question_counts() to authenticated;
grant execute on function public.delete_question(bigint) to authenticated;
grant execute on function public.save_push_subscription(text, text, text) to authenticated;
grant execute on function public.delete_push_subscription(text) to authenticated;
grant execute on function public.touch_updated_at() to authenticated;
grant execute on function public.keep_alive() to anon, authenticated;

-- =====================================================================
-- Erweiterungen: pg_net (Push) und pg_cron (Monatsende, 1. um 7:00 UTC = 8/9 Uhr deutsche Zeit)
-- =====================================================================
do $$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_net') then
    create extension if not exists pg_net;
  end if;
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    create extension if not exists pg_cron;
    perform cron.schedule('obmanns-monatsende', '0 7 1 * *', 'select public.close_month()');
  end if;
end
$$;
